#ifndef __CUSERCHARACINFO_H__
#define __CUSERCHARACINFO_H__

#include <common/defs.h>
#include <common/constants_improved.h>
#include <common/error_codes.h>

// Forward declaration
struct CUserCharacInfo;

// Function declarations (482 functions)

int __cdecl CUserCharacInfo::getCurCharacNo(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacInvenR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacInvenW(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::enableSaveInven(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_charac_level(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IsCurCharacGhost(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_charac_job(CUserCharacInfo *this);
const char *__cdecl CUserCharacInfo::getCurCharacName(CUserCharacInfo *this);
char __cdecl CUserCharacInfo::getCurCharFirstGrowType(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacUsedFatigue(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IncCurCharacEventAddItemCount(CUserCharacInfo *this, unsigned __int16 a2);
int __cdecl CUserCharacInfo::getCurUseBringUpMaterialTotal(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::resetCurUseBringUpMaterialCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurUseBringUpMaterialCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getBringUpRewardFlag(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setBringUpRewardFlag(CUserCharacInfo *this, bool a2);
int __cdecl CUserCharacInfo::getUpgradeSeparateTrueFlag(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getUpgradeSeparateFlaseFlag(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacW(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::enableSaveCharacEtc(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacMaxFatigue(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacMaxPremiumFatigue(CUserCharacInfo *this, unsigned __int16 a2);
CUserCharacInfo *__cdecl CUserCharacInfo::enableSaveQuest(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacCargoR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacCargoW(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::enableSaveCargo(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacExp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacGrowType(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IsFirstTimeLogin(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetWinPoint(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacMoney(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacInvenRefR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacInvenRefW(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::enableSaveCharacStat(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacExp(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::get_pvp_grade(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacStrikerSkillIndex(CUserCharacInfo *this, unsigned __int8 a2);
int __cdecl CUserCharacInfo::setCurCharacTagCharacNo(CUserCharacInfo *this, unsigned int id);
int __cdecl CUserCharacInfo::getTagCharacInvenR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getTagCharacSkillR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacSkillR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacSkillW(CUserCharacInfo *this);
char *__cdecl CUserCharacInfo::getPVPResultRefR(CUserCharacInfo *this);
char *__cdecl CUserCharacInfo::getPVPResultW(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setDemensionInoutValue(CUserCharacInfo *this, unsigned __int8 a2, int id);
int __cdecl CUserCharacInfo::setUltimateInoutValue(CUserCharacInfo *this, char flag, char type);
time_t __cdecl CUserCharacInfo::getCurCharacCreateTime(CUserCharacInfo *this);
CommonTime *__cdecl CUserCharacInfo::set_charac_createtime(CUserCharacInfo *this, time_t timer);
char __cdecl CUserCharacInfo::getCurCharSecondGrowType(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::enableSaveCharacInfo(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::enableSaveCharacManageInfo(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::enableSaveSkill(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::enableSavePvP(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::setSaveCharacOption(CUserCharacInfo *this, bool a2);
int __cdecl CUserCharacInfo::getCurCharacFatigue(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacFatigue(CUserCharacInfo *this, __int16 a2);
int __cdecl CUserCharacInfo::getUserEventCharacterFlag(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurCharacSkillTreeIndex(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::GetCurCharacSkillTreeIndex(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacHelpAbuseComputedRatio(CUserCharacInfo *this, unsigned int id);
int __cdecl CUserCharacInfo::GetReliablePerson(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacStamina(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_charac_10_level_section(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCharacViewState(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::get_charac_guildkey(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::resetGuildCreateFlag(CUserCharacInfo *this);
void *__cdecl CUserCharacInfo::resetTempGuildNameAddr(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCreateGuildName(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCreateGuildAddr(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getGuildMemberGrade(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_guild_create_right(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::set_guild_create_right(CUserCharacInfo *this, unsigned __int8 a2);
int __cdecl CUserCharacInfo::get_charac_memberkey(CUserCharacInfo *this);
_BOOL4 __cdecl CUserCharacInfo::is_connect_upper_member(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_member_pay_tex_money_to_upper(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::set_member_pay_tex_money_to_upper(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::get_member_pay_tex_fatigue_to_upper(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::set_member_pay_tex_fatigue_to_upper(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::GetLoginTick(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurrCharacBlackCount(CUserCharacInfo *this, unsigned int id);
int __cdecl CUserCharacInfo::GetAssaultPlace(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacSuperState(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurCharacChaosPoint(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::SetCurCharacEmotion(CUserCharacInfo *this, __int16 a2);
int __cdecl CUserCharacInfo::SetCurRevengeDungeonCount(CUserCharacInfo *this, unsigned __int8 a2);
int __cdecl CUserCharacInfo::GetCurRevengeDungeonCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacChaosKillTime(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetOpencoin(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::GetOpencoin(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacLuckPoint(CUserCharacInfo *this);
char __cdecl CUserCharacInfo::IncCurCharacLuckPoint(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::GetCurCharacExpertJobType(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurCharacExpertJob(CUserCharacInfo *this, expert_job::CExpertJob *a2);
int __cdecl CUserCharacInfo::GetCurCharacExpertJob(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::isDisguiseCharac(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setDisguiseCharac(CUserCharacInfo *this, bool a2, unsigned __int8 a3, unsigned __int16 a4);
int __cdecl CUserCharacInfo::setDisguiseKind(CUserCharacInfo *this, unsigned __int8 a2);
int __cdecl CUserCharacInfo::setDisguiseIndex(CUserCharacInfo *this, unsigned __int16 a2);
int __cdecl CUserCharacInfo::GetUserPowerWarPoint(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::updateLastItemLimitEditionBuyTime(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::getLastItemLimitEditionBuyTime(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setUpgradeSeparateTrueFlag(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::setUpgradeSeparateFalseFlag(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::getCurChannelEquipslotSwitch(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurExpandEquipslotSwitch(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::incCurUseBringUpMaterialCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_growth_power_reward(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::set_growth_power_reward(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::set_growth_power_exp_reward_right(CUserCharacInfo *this, bool a2);
int __cdecl CUserCharacInfo::setSeriaRoomAniDecoInfo(int id, int value);
CUserCharacInfo *__stdcall CUserCharacInfo::getSeriaRoomAniDecoInfo(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::setConctractOfCubePremiumInfo(CUserCharacInfo *this, bool a2, unsigned __int8 a3);
int __cdecl CUserCharacInfo::IsEndLetheAtLogin(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::set_aura_avatar_option_value(CUserCharacInfo *this, unsigned int id, int value);
int __cdecl CUserCharacInfo::getCurCharacLastPlayTick(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacEventCharacterGrowtype(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacGuildSecede(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacGuildSecede(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::set_charac_guildkey(CUserCharacInfo *this, unsigned int id);
int __cdecl CUserCharacInfo::get_guild_exp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacStamina(CUserCharacInfo *this, unsigned __int8 a2);
int __cdecl CUserCharacInfo::setCurCharacBackupStamina(CUserCharacInfo *this, unsigned __int8 a2);
int __cdecl CUserCharacInfo::getCurrCharacBlackCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetPowerWarLastPlayTime(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::isJoinPowerWar(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setPowerWarHP(CUserCharacInfo *this, unsigned __int16 a2);
int __cdecl CUserCharacInfo::getPowerWarHP(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getStraightVictories(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::incStraightVictories(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::resetStraightVictories(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetAssaultPlace(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::SetAssaultCount(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::GetAssaultCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacChaosPoint(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacChaosModeCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacChaosKillCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacChaosDieCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurCharacSuperState(CUserCharacInfo *this, bool a2);
int __cdecl CUserCharacInfo::GetCurCharacChaosDieTime(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurCharacChaosModeCount(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::SetCurCharacChaosKillCount(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::SetCurCharacChaosDieCount(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::SetCurCharacChaosDieTime(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::SetCurCharacGhost(CUserCharacInfo *this, bool a2);
int __cdecl CUserCharacInfo::IncCurCharacChaosModeCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IncCurCharacChaosKillCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IncCurCharacChaosDieCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IncCurCharacAssaultCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetUserStateByAssault(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurCharacLeaveTimeout(CUserCharacInfo *this, bool a2);
int __cdecl CUserCharacInfo::SetCurCharacChaosKillTime(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::IncPowerWarAssaultCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IncPowerWarAssaultVictoryCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurConditionEventStep(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IncCurConditionEventStep(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurConditionEventRewardStep(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IncCurConditionEventRewardStep(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetProperDungeonClearCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IsProperDungeonUser(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacExpertJobExp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::set_charac_party_bonus_exp(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::set_charac_fatigue_buf_bonus_exp(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::set_charac_member_bonus_exp(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::set_charac_seria_buf_bonus_exp(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::getCurCharacLastPlayTickPowerWar(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacLastPlayTickPowerWar(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::setCurrCharacJoinPower(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::GetCurCharacChaosStateTime(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacEventCharacterGrowtype(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::setCurChannelEquipslotSwitch(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::SetCurCharacExpertJobType(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::SetCurCharacExpertJobExp(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::getCurCharacFatigueGrownUpBuff(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacFatigueGrownUpBuff(CUserCharacInfo *this, unsigned __int16 a2);
int __cdecl CUserCharacInfo::GetFatigueBatteryCharging(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacAddInfoR(CUserCharacInfo *this);
char *__cdecl CUserCharacInfo::getDungeonClearRefW(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::enableSaveDungeonClear(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setStraightVictories(CUserCharacInfo *this, unsigned __int16 a2);
int __cdecl CUserCharacInfo::getTagCharacR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getTagCharacSkillW(CUserCharacInfo *this);
char *__cdecl CUserCharacInfo::getPVPResultRefW(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::reset_is_end_lethe_at_login(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetFirstTimeLogin(CUserCharacInfo *this, bool a2);
CUserCharacInfo *__cdecl CUserCharacInfo::disableSaveInven(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::disableSaveSkill(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::disableSavePvP(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::disableSaveDungeonClear(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::disableSaveCargo(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::incCurCharacMemberBonusFatigue(CUserCharacInfo *this, __int16 a2);
int __cdecl CUserCharacInfo::resetCurCharacMemberBonusFatigue(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacMemberBonusFatigue(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacLastPlayDungeonIndex(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::setUserEventCharacterFlag(CUserCharacInfo *this, unsigned __int8 a2);
CReliablePerson *__cdecl CUserCharacInfo::setCurCharacTradeGoldDaily(CUserCharacInfo *this, unsigned int id);
CUserCharacInfo *__cdecl CUserCharacInfo::SetReliablePerson(CUserCharacInfo *this, bool a2);
CUserCharacInfo *__cdecl CUserCharacInfo::SetOverTradeGoldCount(CUserCharacInfo *this, unsigned int id);
int __cdecl CUserCharacInfo::get_charac_exp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setGuildCreateFlag(CUserCharacInfo *this, unsigned __int16 a2);
int __cdecl CUserCharacInfo::setGuildMemberGrade(CUserCharacInfo *this, unsigned __int8 a2);
int __cdecl CUserCharacInfo::set_charac_memberkey(CUserCharacInfo *this, unsigned int id);
int __cdecl CUserCharacInfo::set_connect_upper_member(CUserCharacInfo *this, unsigned int id);
int __cdecl CUserCharacInfo::SetLoginTick(CUserCharacInfo *this, int id);
CUserCharacInfo *__cdecl CUserCharacInfo::SetCharacStartPlayTick(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::needCurCharacCheckOverEquip(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::resetCurCharacOverEquipFlag(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetPowerWarProcessInfoLastUpdateTime(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::SetCurCharacRevengeData(CUserCharacInfo *this, unsigned __int8 a2, unsigned __int8 a3);
int __cdecl CUserCharacInfo::VillageAttack_DBUpdate(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::VillageAttack_NotDBUpdate(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurVillageAttackCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::ClearCurConditionEventStep(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurConditionEventStep(CUserCharacInfo *this, __int16 a2);
int __cdecl CUserCharacInfo::ClearCurConditionEventRewardStep(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurConditionEventRewardStep(CUserCharacInfo *this, __int16 a2);
int __cdecl CUserCharacInfo::ClearProperDungeonClearCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetProperDungeonClearCount(CUserCharacInfo *this, __int16 a2);
int __cdecl CUserCharacInfo::SetCurCharacLuckPointUpdateTimeCount(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::SetOneDayLetheFlag(CUserCharacInfo *this, unsigned __int8 a2);
int __cdecl CUserCharacInfo::SetIsInitSkillFlag(CUserCharacInfo *this, bool a2);
int __cdecl CUserCharacInfo::SetOneDayLetheFlag2ND(CUserCharacInfo *this, unsigned __int8 a2);
int __cdecl CUserCharacInfo::SetIsInitSkillFlag2ND(CUserCharacInfo *this, bool a2);
int __cdecl CUserCharacInfo::ResetPowerWarAssaultRecord(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetPowerWarAssaultCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetPowerWarAssaultVictoryCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurExpEquipSlotStat(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::getLinkCharacSlotIndex(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurUseBringUpMaterialTotal(CUserCharacInfo *this, unsigned __int8 a2);
int __cdecl CUserCharacInfo::set_aura_avatar_option(CUserCharacInfo *this, stAuraAvatarOption *a2);
_WORD *__cdecl CUserCharacInfo::setCharacOption(CUserCharacInfo *this, CharacterOption *a2);
int __cdecl CUserCharacInfo::initContractOfCubePremiumInfo(CUserCharacInfo *this, bool a2, unsigned __int8 a3);
char *__cdecl CUserCharacInfo::getPVPResultR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacHelpAbuseComputedRatio(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::DecCurCharacLuckPoint(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::GetCurCharacOnlinePreliminaryTeam(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurCharacOnlinePreliminaryTeam(CUserCharacInfo *this, online_preliminary::COnlinePreliminaryTeam *a2);
int __cdecl CUserCharacInfo::IsCurCharacLeaveTimeout(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getDemensionInoutValue(CUserCharacInfo *this, unsigned __int8 a2);
int __cdecl CUserCharacInfo::subDemensionInoutValue(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::subUltimateInoutValue(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::getBloodBestRoundRecord(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getBloodBestTimeRecord(CUserCharacInfo *this);
char *__cdecl CUserCharacInfo::getDungeonClearRefR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacLastPlayDungeonIndex(CUserCharacInfo *this, unsigned int id);
int __cdecl CUserCharacInfo::getMemberDungeonFlag(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setMemberDungeonFlag(CUserCharacInfo *this, bool a2);
int __cdecl CUserCharacInfo::getCurCharacTutorialFlag(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::set_level_before_dungeon(CUserCharacInfo *this, __int16 a2);
int __cdecl CUserCharacInfo::get_guild_temp_exp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_connect_upper_member(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::DecreaseRevengeDungeonTicket(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IncProperDungeonClearCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetProperDungeonUser(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::ClearProperDungeonUser(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurCharacDungeonPlayCount(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::GetCurCharacDungeonPlayCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IncCurCharacDungeonPlayCount(CUserCharacInfo *this);
long double __cdecl CUserCharacInfo::GetExpAffectRate(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IsExpItemAffected(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetOneDayLetheFlag(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetOneDayLetheFlag2ND(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacEffectItemListR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_pvp_result_exp_point(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_pvp_result_oldexp_point(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::isSaveInven(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacLuckPointUpdateTimeCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IncCurCharacLuckPointUpdateTimeCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetExpAffectItemEffect(CUserCharacInfo *this, bool a2, float a3);
int __cdecl CUserCharacInfo::GetCharacPlayTick(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacVill(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacVill(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::UseFinishPoint(CUser **this, int id);
long double __cdecl CUserCharacInfo::GetWarAreaKillCountTotal(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetFinishPoint(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::ChangeFinishPoint(CUserCharacInfo *this, int id);
long double __cdecl CUserCharacInfo::GetWarAreaKillCount(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::GetFinishPointTotal(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::InitFinishPoint(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::WarAreaKill(CUser **this, int id, int value, float a4);
int __cdecl CUserCharacInfo::DecreaseWarPoint(CUserCharacInfo *this, int id);
void __cdecl CUserCharacInfo::set_uppermember_exp_level(CUserCharacInfo *this, unsigned __int8 a2);
int __cdecl CUserCharacInfo::add_guild_temp_exp(CUserCharacInfo *this, __int16 a2);
int __cdecl CUserCharacInfo::reset_guild_temp_exp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::add_guild_exp(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::reset_guild_exp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::add_guild_today_exp(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::reset_guild_today_exp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_charac_level_before_dungeon(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::reset_level_before_dungeon(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::set_guild_exp(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::GetCurCharacOnlinePreliminaryTeamId(CUserCharacInfo *this);
char *__cdecl CUserCharacInfo::GetCurCharacOnlinePreliminaryTeamName(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GainCurCharacChaosExp(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::AddCurCharacChaosPoint(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::SubCurCharacChaosPoint(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::GmSetCurCharacChaosPoint(CUserCharacInfo *this, int id);
void __cdecl CUserCharacInfo::getSeparatedTextUnits(int id, char **a2, int value, char *needle, int count);
int __cdecl CUserCharacInfo::DieCurCharac(CUserCharacInfo *this, int id, CUser *user);
int __cdecl CUserCharacInfo::LiveCurCharac(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IsAvailableCurCharacTradeGoldDaily(CUserCharacInfo *this, unsigned int id);
int __cdecl CUserCharacInfo::SetCurCharacLuckPoint(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::GetCurCharacMaxEquipLevel(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurCharacMaxEquipLevel(CUserCharacInfo *this, int id);
void *__cdecl CUserCharacInfo::resetCharacTutorialFlag(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacTutorialFlag(CUserCharacInfo *this, unsigned int id);
_BOOL4 __cdecl CUserCharacInfo::getCurCharacEscaladeTutorialFlag(CUserCharacInfo *this, unsigned int id);
_BOOL4 __cdecl CUserCharacInfo::IsBusyDisjointStore(CUserCharacInfo *this);
void __cdecl CUserCharacInfo::CUserCharacInfo(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::resetSaveFlags(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::setCurCharac(CUserCharacInfo *charac_info, int id);
CUserCharacInfo *__cdecl CUserCharacInfo::setTagCharac(CUserCharacInfo *this, _Charac_info *a2);
CUserCharacInfo *__cdecl CUserCharacInfo::useWinPoint(CUserCharacInfo *charac_info, int id);
int __cdecl CUserCharacInfo::setCurCharGrowthType(CUserCharacInfo *this, char flag, int id);
int __cdecl CUserCharacInfo::setCurCharChangingGrowthType(CUserCharacInfo *this, char flag, int id);
int __cdecl CUserCharacInfo::get_level_up_exp(CUserCharacInfo *this, int id);
void CUserCharacInfo::calcHelpAbuseRatioBeforeLevelUp();
int __cdecl CUserCharacInfo::calcHelpAbuseRatio(CUserCharacInfo *this, unsigned int id, int value);
unsigned int __cdecl CUserCharacInfo::calcCurCharacSchoolPoint(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::IncFatigueBatteryCharging(CUserCharacInfo *this, __int16 a2);
int __cdecl CUserCharacInfo::DecFatigueBatteryCharging(CUserCharacInfo *this, __int16 a2);
int __cdecl CUserCharacInfo::calc_disp_help_abuse_ratio(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::EnablePeriodExpDouble(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::EnablePeriodExpItem(CUserCharacInfo *this);
bool __cdecl CUserCharacInfo::ClearUselessCooltimeItem(CUserCharacInfo *this, unsigned int id);
bool __cdecl CUserCharacInfo::ClearUselessEffectItem(CUserCharacInfo *this, unsigned int id);
_BOOL4 __cdecl CUserCharacInfo::isSetGuildCreateFlag(CUserCharacInfo *this, unsigned __int16 a2);
int __cdecl CUserCharacInfo::resetCharGuildInfo(CUserCharacInfo *this);
bool __cdecl CUserCharacInfo::GetContinuousItemInfo(CUserCharacInfo *charac_info, int id);
_BOOL4 __cdecl CUserCharacInfo::isExistItem(CUserCharacInfo *this, char *a2);
_BOOL4 __cdecl CUserCharacInfo::FindItemLock(int id, char flag, _DWORD *a3, int *a4, int value);
int __cdecl CUserCharacInfo::IncreasePowerWarPoint(CUserCharacInfo *this, __int16 a2);
int __cdecl CUserCharacInfo::DecreasePowerWarPoint(CUserCharacInfo *this, __int16 a2);
int __cdecl CUserCharacInfo::setBloodBestRecord(CUserCharacInfo *this, unsigned int id, int value, int count, bool a5);
int __cdecl CUserCharacInfo::SetInvisible(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetVisible(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_charac_visible_values(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::set_charac_visible_values(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::set_charac_visible_grow_avatar(CUserCharacInfo *this, bool a2);
int __cdecl CUserCharacInfo::set_charac_visible_teleport_(CUserCharacInfo *this, bool a2);
_BOOL4 __cdecl CUserCharacInfo::get_charac_visible_grow_avatar(CUserCharacInfo *this);
_BOOL4 __cdecl CUserCharacInfo::IsCurCharacVisible(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setPremiumBonusExp(CUserCharacInfo *this, unsigned int id, int value);
int __cdecl CUserCharacInfo::getPremiumBonusExp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::resetPremiumBonusExp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setWeekendBonusFatigue(CUserCharacInfo *this, unsigned __int16 a2);
int __cdecl CUserCharacInfo::setWeekendBonusExp(CUserCharacInfo *this, unsigned int id, int value);
int __cdecl CUserCharacInfo::getWeekendBonusExp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::resetWeekendBonusExp(CUserCharacInfo *this);
char __cdecl CUserCharacInfo::checkBonusPoint(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getWpBonusPoint(CUserCharacInfo *this, WpBonusPointResult *a2);
int __cdecl CUserCharacInfo::getExpBonusPoint(CUserCharacInfo *this, ExpBonusPointResult *a2);
void *__cdecl CUserCharacInfo::resetBonusPoint(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacChaosResponTime(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurCharacChaosResponTime(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::GetCurCharacAssaultMoney(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurCharacAssaultMoney(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::GetCurCharacAssaultedUserId(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurCharacAssaultedUserId(CUserCharacInfo *this, unsigned __int16 a2);
_WORD *__cdecl CUserCharacInfo::SetCurCharacOption(CUserCharacInfo *this, CharacterOption *a2);
int __cdecl CUserCharacInfo::resetBlueMarbleEnterCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setBlueMarbleEnterCount(CUserCharacInfo *this, unsigned __int8 a2);
int __cdecl CUserCharacInfo::increaseBlueMarbleEnterCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getBlueMarbleEnterCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::resetBlueMarbleUserDeadCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::increaseBlueMarbleUserDeadCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getBlueMarbleUserDeadCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacStrikerSkillIndex(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacTagCharacNo(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getTagCharacW(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getTagCharacInvenW(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getTagCharacAddInfoR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getTagCharacCargoW(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getTagCharacCargoR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacAddInfoRefR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacAddInfoW(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacAddInfoRefW(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacLastPlayTick(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::IsSaveDemensionInoutValue(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetSaveDemensionInoutValue(CUserCharacInfo *this, bool a2);
int __cdecl CUserCharacInfo::IsSaveBloodInoutValue(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetSaveBloodInoutValue(CUserCharacInfo *this, bool a2);
int __cdecl CUserCharacInfo::getUltimateInoutValue(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::isBloodBestRecordUpdate(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setBloodBestRecordUpdate(CUserCharacInfo *this, bool a2);
int __cdecl CUserCharacInfo::getCurCharacVill4Save(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacVillPrev(CUserCharacInfo *this);
char *__cdecl CUserCharacInfo::getBattleRecordRefR(CUserCharacInfo *this);
char *__cdecl CUserCharacInfo::getBattleRecordRefW(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::disableSaveCharacInfo(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::disableSaveCharacStat(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::disableSaveCharacEtc(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::disableSaveCharacManageInfo(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::disableSaveQuest(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::disableSaveBattleRecord(CUserCharacInfo *this);
CUserCharacInfo *__cdecl CUserCharacInfo::enableSaveBattleRecord(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::isSaveCharacInfo(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IsSaveCharacStat(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::isSaveCharacEtc(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IsSaveCharacManageInfo(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::isSaveSkill(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::isSavePvP(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::isSaveQuest(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::isSaveDungeonClear(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::isSaveBattleRecord(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::isSaveCargo(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::isSaveCharacOption(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetFatigue(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::decCurCharacFatigueGrownUpBuff(CUserCharacInfo *this, unsigned int id);
int __cdecl CUserCharacInfo::resetCharacFatigueGrownUpBuff(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacPremiumFatigue(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacPremiumFatigue(CUserCharacInfo *this, unsigned __int16 a2);
int __cdecl CUserCharacInfo::getCurCharacMaxPremiumFatigue(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::incCurCharacUsedFatigue(CUserCharacInfo *this, unsigned __int16 a2);
int __cdecl CUserCharacInfo::resetCurCharacUsedFatigue(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::ResetCurCharacEventItemCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacEventItemCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::ResetCurCharacEventAddItemCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacEventAddItemCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::resetCurCharacSchoolPoint(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacSchoolPoint(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacDungeonHelpAbuseRatio(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacDungeonHelpAbuseExp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacEscaladeTutorialFlag(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacTradeGoldTotal(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacTradeGoldTotalBillion(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacTradeGoldDaily(CUserCharacInfo *this);
CReliablePerson *__cdecl CUserCharacInfo::IncrementCurCharacTradeGoldDaily(CUserCharacInfo *this, unsigned int id);
int __cdecl CUserCharacInfo::GetOverTradeGoldCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::addCurcharacStamina(CUserCharacInfo *this, unsigned __int8 a2);
int __cdecl CUserCharacInfo::get_charac_party_bonus_exp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacCoin(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacPayCoin(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurCharacEventCoin(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurCharacLevel(CUserCharacInfo *this, __int16 a2);
int __cdecl CUserCharacInfo::incCurCharacLevel(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::decCurCharacLevel(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::addCurCharacExp(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::subtractCurCharacExp(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::getRequestRenameState(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_guild_today_exp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_uppermember_exp_level(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_charac_fatigue_buf_bonus_exp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::get_charac_member_bonus_exp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::add_member_pay_tex_money_to_upper(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::add_member_pay_tex_fatigue_to_upper(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::GetCharacStartPlayTick(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacChaosExp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacEmotion(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IsVillageAttackDBUpdate(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetCurCharacAssaultFatigueCount(CUserCharacInfo *this, int id);
int __cdecl CUserCharacInfo::GetCurCharacAssaultFatigueCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IncCurCharacAssaultFatigueCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::ResetCurCharacDungeonPlayCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacCoolTimeItemList(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacCoolTimeItemListR(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacEffectItemList(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetIsAffectedExpDouble(CUserCharacInfo *this, bool a2);
int __cdecl CUserCharacInfo::GetCurCharacBackupSkill(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurCharacBackupSkill2ND(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getDisguiseKind(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getDisguiseIndex(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetCurExEquipSlotStat(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setLinkCharacSlotIndex(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::getCharacLinkType(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCharacLinkBonusExp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCharacLinkBonusExp(CUserCharacInfo *this, unsigned int id);
int __cdecl CUserCharacInfo::getCharacLinkBonusGold(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCharacLinkBonusGold(CUserCharacInfo *this, unsigned int id);
int __cdecl CUserCharacInfo::getSkillCommand(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getCurEquipslotFlag(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::setCurEquipslotFlag(CUserCharacInfo *this, char flag);
int __cdecl CUserCharacInfo::get_charac_seria_buf_bonus_exp(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::is_growth_power_exp_reward_right(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::getContractOfCubePremiumInfo(CUserCharacInfo *this, bool *a2, unsigned __int8 *a3);
int __cdecl CUserCharacInfo::isSavedPremiumCubeInfo(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::disableSavedPremiumCubeInfo(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::SetIsEndLetheAtLogin(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::IncVillageAttackCount(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetPowerWarLastPlayTime(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::GetPowerWarProcessInfoLastUpdateTime(CUserCharacInfo *this);
int __cdecl CUserCharacInfo::ResetRevengeDungeonClear(CUserCharacInfo *this);

#endif // __CUSERCHARACINFO_H__
