#ifndef __CUSER_H__
#define __CUSER_H__

#include <common/defs.h>
#include <common/constants_improved.h>
#include <common/error_codes.h>

// Forward declaration
struct CUser;

// Function declarations (961 functions)

int __cdecl CUser::GetUID(CUser *this);
int __cdecl CUser::GetServerGroup(CUser *this);
__int16 __cdecl CUser::CheckInTrade(CUser *this);
__int16 __cdecl CUser::CheckInParty(CUser *this);
__int16 __cdecl CUser::checkInBlueMarble(CUser *this);
CUser *__cdecl CUser::setBlueMarbleIndex(CUser *this, __int16 a2);
int __cdecl CUser::getBlueMarbleIndex(CUser *this);
int __cdecl CUser::get_acc_id(CUser *this);
int __cdecl CUser::get_unique_id(CUser *this);
int __cdecl CUser::get_state(CUser *this);
int __cdecl CUser::GetCharacExpandData(int id, unsigned int value);
int __cdecl CUser::GetAccountLastPlayTime(CUser *this);
_BOOL4 __cdecl CUser::isAffectedPremium(int id, int value);
char *__cdecl CUser::getHackAnalyzer(CUser *this);
int __cdecl CUser::SetETC(CUser *this, __int16 a2, int id);
CUser *__cdecl CUser::set_multiboxLotteryItemFailCnt(CUser *this, int id);
int __cdecl CUser::inc_multiboxLotteryItemFailCnt(CUser *this);
int __cdecl CUser::GetCera(CUser *this);
int __cdecl CUser::GetAge(CUser *this);
char *__cdecl CUser::GetUserName(CUser *this);
char *__cdecl CUser::GetSsnString(CUser *this);
char *__cdecl CUser::GetUserEMail(CUser *this);
char *__cdecl CUser::get_acc_name(CUser *this);
int __cdecl CUser::GetPCRoomNo(CUser *this);
CUser *__cdecl CUser::incPcRoomPlayTimeRewardCnt(CUser *this);
int __cdecl CUser::getPcRoomPlayTimeRewardCnt(CUser *this);
CUser *__cdecl CUser::resetTotalPcRoomPlayTime(CUser *this);
int __cdecl CUser::getTotalPcRoomPlayTime(CUser *this);
CUser *__cdecl CUser::IncCurCharacUsedFatigueQuantity(CUser *this, unsigned int id);
CUser *__cdecl CUser::IncCurCharacUsedGiftFatigueQuantity(CUser *this, unsigned int id);
int __cdecl CUser::GetCurCharacUsedGiftFatigueQuantity(CUser *this);
CUser *__cdecl CUser::SetChangedGiftFatigueQuantity(CUser *this, bool a2);
CUser *__cdecl CUser::setPcRoomPlayStartTime(CUser *this, unsigned int id);
int __cdecl CUser::IsGameMasterMode(CUser *this);
int __cdecl CUser::EnableCharacInfo(int id, int value);
char *__cdecl CUser::GetPremiumInfo(CUser *this);
bool __cdecl CUser::IsHavePremiumAdvantage(CUser *this);
int __cdecl CUser::DisableCharacInfo(int id, int value);
int __cdecl CUser::GetLastLoginCharacNo(CUser *this);
int __cdecl CUser::GetLastLoginChannelNo(CUser *this);
int __cdecl CUser::IsValidLastLoginCharac(CUser *this);
CUser *__cdecl CUser::setAdvanceAltarIndex(CUser *this, __int16 a2);
int __cdecl CUser::get_posX(CUser *this);
int __cdecl CUser::get_posY(CUser *this);
int __cdecl CUser::get_direction(CUser *this);
int __cdecl CUser::isGMUser(CUser *this);
char *__cdecl CUser::getCurCharacQuestW(CUser *this);
CUser *__cdecl CUser::SetRevivalTime(CUser *this, int id);
int __cdecl CUser::GetRevivalTime(CUser *this);
CUser *__cdecl CUser::SetUseAPCPotionTime(CUser *this, int id);
CUser *__cdecl CUser::setBossTowerIndex(CUser *this, __int16 a2);
char *__cdecl CUser::getGarenaAuthData(CUser *this);
CUser *__cdecl CUser::SetCera(CUser *this, unsigned int id);
int __cdecl CUser::UseCera(CUser *this, unsigned int id);
CUser *__cdecl CUser::resetUsedCera(CUser *this);
CUser *__cdecl CUser::addUsedCera(CUser *this, unsigned int id);
int __cdecl CUser::getUsedCera(CUser *this);
char *__cdecl CUser::getCurCharacQuestR(CUser *this);
CUser *__cdecl CUser::set_ontime_last_recv_idx(CUser *this, int id);
int __cdecl CUser::get_ontime_last_recv_idx(CUser *this);
CUser *__cdecl CUser::set_update_ontime_last_recv_idx(CUser *this);
bool __cdecl CUser::IsWaitingStateCharac(CUser *this, unsigned int id);
CUser *__cdecl CUser::SetLoadRentalInfoFromExchange(CUser *this, bool a2);
char *__cdecl CUser::GetAccountCargo(CUser *this);
bool __cdecl CUser::IsExistAccountCargo(CUser *this);
char *__cdecl CUser::GetGameOptionRef(CUser *this);
CUser *__cdecl CUser::setBreakAwayDungeonClearCnt(CUser *this, int id);
int __cdecl CUser::getBreakAwayDungeonClearCnt(CUser *this);
CUser *__cdecl CUser::setBreakAwayQuestTime(CUser *this, unsigned int id);
CUser *__cdecl CUser::setGmQuestFlag(CUser *this, bool a2);
int __cdecl CUser::getOnlinePreliminaryCharacNo(CUser *this);
int __cdecl CUser::getBackupSeed(CUser *this);
int __cdecl CUser::getPowerSide(CUser *this);
char *__cdecl CUser::getClientHWSpec(CUser *this);
int __cdecl CUser::getAntibotKey(CUser *this);
int __cdecl CUser::get_multiboxLotteryItemFailCnt(CUser *this);
CUser *__cdecl CUser::set_local_ip_address(CUser *this, int id);
char *__cdecl CUser::getWebAddress(CUser *this);
char *__cdecl CUser::getSecurityCard(CUser *this);
char *__cdecl CUser::getPad(CUser *this);
int __cdecl CUser::isHackUser(CUser *this);
int __cdecl CUser::isHackUserTimer(CUser *this);
CUser *__cdecl CUser::SetLastLoginCharacNo(CUser *this, int id);
CUser *__cdecl CUser::SetLastLoginChannelNo(CUser *this, int id);
CUser *__cdecl CUser::SetValidLastLoginCharac(CUser *this, bool a2);
CUser *__cdecl CUser::IncChecksumAnswerCount(CUser *this);
int __cdecl CUser::lock(pthread_mutex_t *this);
int __cdecl CUser::unlock(pthread_mutex_t *this);
int __cdecl CUser::getRegTime(CUser *this);
int __cdecl CUser::GetSeedFromDate(CUser *this);
int __cdecl CUser::GetSchoolNo(CUser *this);
CUser *__cdecl CUser::SetLoginTime(CUser *this, int id);
CUser *__cdecl CUser::SetLogInOutState(CUser *this, unsigned __int8 a2);
int __cdecl CUser::GetTradeSpace(CUser *this);
int __cdecl CUser::GetPartyIndex(CUser *this);
__int16 __cdecl CUser::CheckInPvp(CUser *this);
int __cdecl CUser::GetPvpIndex(CUser *this);
int __cdecl CUser::GetWarRoomIndex(CUser *this);
int __cdecl CUser::getBossTowerIndex(CUser *this);
int __cdecl CUser::SetGMUpgradeMode(int id, int value);
int __cdecl CUser::get_charac_name(CUser *this, int id);
int __cdecl CUser::GetCharacJob(CUser *this, int id);
bool __cdecl CUser::CheckPossibleRequestRenameState(CUser *this, int id);
int __cdecl CUser::SetCharacViewState(CUser *this, int id);
int __cdecl CUser::SetCharacViewState(CUser *this, int id, int value);
int __cdecl CUser::GetCharacViewState(CUser *this, int id);
int __cdecl CUser::SetServerGroup(int id, int value);
CUser *__cdecl CUser::SetAge(CUser *this, unsigned int id);
bool __cdecl CUser::IsState(int id, int value);
int __cdecl CUser::get_charac_count(CUser *this);
int __cdecl CUser::get_pvp_exp_of_week(CUser *this);
CUser *__cdecl CUser::decre_check_count(CUser *this);
char *__cdecl CUser::GetGuildDBInfo(CUser *this);
_BOOL4 __cdecl CUser::IsGuildMaster(CUser *this);
int __cdecl CUser::GetGuildPowerWarPoint(CUser *this);
CUser *__cdecl CUser::DecreaseGuildPowerWarPoint(CUser *this, unsigned int id);
bool __cdecl CUser::IsExistGuildAgit(CUser *this);
int __cdecl CUser::GetGuildCargoCapacity(CUser *this);
CUser *__cdecl CUser::SetDebugCommand(CUser *this, int id);
int __cdecl CUser::GetMailBox(CUser *this);
int __cdecl CUser::isHumanCertified(CUser *this);
CUser *__cdecl CUser::setHumanCertified(CUser *this, bool a2);
CUser *__cdecl CUser::OnRecvEvent(CUser *this);
int __cdecl CUser::SellItemTimeChecker(CUser *this, unsigned int id, unsigned int value);
int __cdecl CUser::GetItemTimeChecker(CUser *this, unsigned int id, signed __int16 a3, signed __int16 a4, unsigned int value);
int __cdecl CUser::GetItemSerialChecker(CUser *this, signed __int16 a2, signed __int16 a3, int id);
int __cdecl CUser::getLastLotteryTime(CUser *this);
CUser *__cdecl CUser::setLastLotteryTime(CUser *this, unsigned int id);
CUser *__cdecl CUser::resetCleanpadFailCnt(CUser *this);
bool __cdecl CUser::isCleanPadVerifyLimit(CUser *this);
char *__cdecl CUser::getHades(CUser *this);
char *__cdecl CUser::GetHackCheck(CUser *this);
char *__cdecl CUser::GetCSHashSet(CUser *this);
CUser *__cdecl CUser::IncreaseUsedCoinCount(CUser *this);
CUser *__cdecl CUser::SetDeleteEventDungeonInvitation(CUser *this, bool a2);
int __cdecl CUser::getCharacSlotLimit(CUser *this);
int __cdecl CUser::getSlotEffectCount(CUser *this);
CUser *__cdecl CUser::setSlotEffectCount(CUser *this, unsigned __int8 a2);
int __cdecl CUser::getCharacAntibotSerialNum(CUser *this);
CUser *__cdecl CUser::setCharacAntibotSerialNum(CUser *this, int id);
CUser *__cdecl CUser::InitReceivedRequestType(CUser *this);
CUser *__cdecl CUser::SetReceivedRequestType(CUser *this, char flag);
int __cdecl CUser::GetReceivedRequestType(CUser *this);
char *__cdecl CUser::getCurCharacQuestRefR(CUser *this);
int __cdecl CUser::GetDebugCommand(CUser *this);
char *__cdecl CUser::GetPICSMap(CUser *this);
char *__cdecl CUser::GetPIReceiverManager(CUser *this);
char *__cdecl CUser::GetPISenderManager(CUser *this);
int __cdecl CUser::GetNonClientFlag(CUser *this);
CUser *__cdecl CUser::SetNonClientFlag(CUser *this, bool a2);
int __cdecl CUser::GetNonClientRandInt(CUser *this);
CUser *__cdecl CUser::SetNonClientRandInt(CUser *this, int id);
CUser *__cdecl CUser::incCharacSlotLimit(CUser *this, unsigned __int8 a2);
CUser *__cdecl CUser::setStdDropRate(CUser *this, int id);
int __cdecl CUser::isRestingUser(CUser *this);
void *__cdecl CUser::DeleteCargo(CUser *this);
int __cdecl CUser::GetCharacExpandDataR(int id, unsigned int value);
CUser *__cdecl CUser::SetSaveRentalInfoToExchange(CUser *this, bool a2);
int __cdecl CUser::IsReturnUserFirstLogin(CUser *this);
int __cdecl CUser::IsProgLogout(CUser *this);
__int16 __cdecl CUser::CheckInWarRoom(CUser *this);
__int16 __cdecl CUser::checkInDeathTower(CUser *this);
int __cdecl CUser::getDeathTowerIndex(CUser *this);
__int16 __cdecl CUser::checkInBossTower(CUser *this);
__int16 __cdecl CUser::checkInAdvanceAltar(CUser *this);
int __cdecl CUser::getAdvanceAltarIndex(CUser *this);
CUser *__cdecl CUser::SetSlotIDX(CUser *this, __int16 a2);
int __cdecl CUser::GetIncreID(CUser *this);
CUser *__cdecl CUser::SetIncreID(CUser *this, __int16 a2);
CUser *__cdecl CUser::set_unique_id(CUser *this, unsigned __int16 a2);
int __cdecl CUser::getPunishTradeAlert(CUser *this);
CUser *__cdecl CUser::set_position(CUser *this, unsigned __int16 a2, unsigned __int16 a3, char flag);
int __cdecl CUser::GetUserState(CUser *this);
int __cdecl CUser::GetAutoClientRate(CUser *this);
int __cdecl CUser::getAddIndependentDropRateFromPremium(int id, unsigned int value, unsigned int count);
int __cdecl CUser::setBreakAwayRewardOrder(int id, int value);
int __cdecl CUser::getBreakAwayRewardOrder(CUser *this);
int __cdecl CUser::getBreakAwayAccureCera(CUser *this);
CUser *__cdecl CUser::setBreakAwayRewardData(CUser *this, bool a2);
_DWORD *__cdecl CUser::setBreakAwayRewards(CUser *this, const STBreakAwayRewards *a2);
char __cdecl CUser::ClearChildrensDayEvent(CUser *this);
CUser *__cdecl CUser::SetChildrensDayEventValue(CUser *this, int id, int value, int count);
_BOOL4 __cdecl CUser::IsOKChildrensDayEventCondition(CUser *this);
int __cdecl CUser::GetChildrensDayEventTargetItemSlot(CUser *this, int id);
int __cdecl CUser::GetChildrensDayEventTargetItemPeriod(CUser *this, int id);
CUser *__cdecl CUser::set_cera_item_order_no(CUser *this, unsigned int id);
int __cdecl CUser::get_cera_item_order_no(CUser *this);
CUser *__cdecl CUser::setChattingMessageCount(CUser *this, int id);
CUser *__cdecl CUser::setDeathTowerIndex(CUser *this, __int16 a2);
CUser *__cdecl CUser::SetGameMasterCharacter(CUser *this, CGameMasterCharacter *a2);
CUser *__cdecl CUser::setHackUserTimer(CUser *this);
CUser *__cdecl CUser::setHackUserFlag(CUser *this);
int __cdecl CUser::getSecuType(CUser *this);
char *__cdecl CUser::UpdateCharacNameInMercenary(CUser *this, unsigned int id, std::string *a3);
int __cdecl CUser::CheckLoadRentalInfoFromExchange(CUser *this);
CUser *__cdecl CUser::SetFirstLogin(CUser *this);
int __cdecl CUser::getBreakAwayQuestTime(CUser *this);
CUser *__cdecl CUser::setBreakAwayAccureCera(CUser *this, int id);
int __cdecl CUser::isBreakAwayRewardData(CUser *this);
char *__cdecl CUser::getBreakAwayRewards(CUser *this);
int __cdecl CUser::getBreakAwayRewardItemId(CUser *this);
int __cdecl CUser::getBreakAwayRewardAItemCnt(CUser *this);
int __cdecl CUser::getBreakAwayRewardItemOrder(CUser *this);
CUser *__cdecl CUser::setBreakAwayRewardItemId(CUser *this, int id);
CUser *__cdecl CUser::setBreakAwayRewardAItemCnt(CUser *this, int id);
int __cdecl CUser::getUserBreakAwayRewardLuckPoint(CUser *this);
CUser *__cdecl CUser::setUserBreakAwayRewardLuckPoint(CUser *this, int id);
CUser *__cdecl CUser::setJoinedSchoolPointEvent(CUser *this, bool a2);
CUser *__cdecl CUser::setTournamentAccount(CUser *this, bool a2);
int __cdecl CUser::isTournamentAccount(CUser *this);
int __cdecl CUser::setOnlinePreliminaryServerGroup(int id, int value);
CUser *__cdecl CUser::setOnlinePreliminaryCharacNo(CUser *this, unsigned int id);
CUser *__cdecl CUser::setOnlinePreliminaryPlayType(CUser *this, int id);
int __cdecl CUser::getOnlinePreliminaryPlayType(CUser *this);
CUser *__cdecl CUser::SetPCRoomNo(CUser *this, unsigned int id);
CUser *__cdecl CUser::SetReturnUser(CUser *this);
CUser *__cdecl CUser::ResetReturnUser(CUser *this);
CUser *__cdecl CUser::SetReturnUserFirstUserLogin(CUser *this, bool a2);
int __cdecl CUser::GetReturnUserExpireTime(CUser *this);
CUser *__cdecl CUser::SetReturnUserExpireTime(CUser *this, int id);
CUser *__cdecl CUser::EnableSaveMemberBonusFatigue(CUser *this);
CUser *__cdecl CUser::incAccountMemberBonusFatigue(CUser *this, __int16 a2);
CUser *__cdecl CUser::resetAccountMemberBonusFatigue(CUser *this);
int __cdecl CUser::getAccountMemberBonusFatigue(CUser *this);
CUser *__cdecl CUser::setPcRoomAuth(CUser *this, bool a2);
CUser *__cdecl CUser::SetVillageAttackedReward(CUser *this, bool a2);
char *__cdecl CUser::getDungeonGainedGold(CUser *this);
CUser *__cdecl CUser::setAntibotKey(CUser *this, int id);
int __cdecl CUser::getClientVersion(CUser *this);
CUser *__cdecl CUser::setClientVersion(CUser *this, unsigned int id);
char *__cdecl CUser::fillUserInfo4Antibot(CUser *this);
char *__cdecl CUser::getUserInfo4Antibot(CUser *this);
CUser *__cdecl CUser::SetAccountLastPlayTime(CUser *this, int id);
int __cdecl CUser::get_public_ip_address(CUser *this);
char *__cdecl CUser::setWebAddress(CUser *this, char *src);
unsigned __int64 __cdecl CUser::setTotalHackUserTradeGold(CUser *this, unsigned __int64 a2);
CUser *__cdecl CUser::setTotalHackUserTradeCnt(CUser *this, unsigned int id);
CUser *__cdecl CUser::SetReportMannerlessUserCount(CUser *this, int id);
int __cdecl CUser::GetChecksumAnswerCount(CUser *this);
CUser *__cdecl CUser::setHangameUser(CUser *this, bool a2);
int __cdecl CUser::isHangameUser(CUser *this);
CUser *__cdecl CUser::setRegDate(CUser *this, unsigned int id);
CUser *__cdecl CUser::setRegTime(CUser *this, int id);
char *__cdecl CUser::SetUserDetailInfo(CUser *this, char *src, char *a3, char *a4);
bool __cdecl CUser::SetDailyBadge(CUser *this, __int16 *a2);
CUser *__cdecl CUser::SetSchoolNo(CUser *this, unsigned int id);
CUser *__cdecl CUser::SetRating(CUser *this, float a2);
int __cdecl CUser::GetTutorialSkipable(CUser *this);
CUser *__cdecl CUser::SetTutorialSkipable(CUser *this, unsigned __int8 a2);
int CUser::IsPCRoomUser();
int __cdecl CUser::GetLogInOutState(CUser *this);
char *__cdecl CUser::getAcccountHackInfo(CUser *this);
int __cdecl CUser::getStdDropRate(CUser *this);
int __cdecl CUser::SetCharacViewStateByCharacNo(CUser *this, int id, int value);
int __cdecl CUser::getCharacLevelByCharacNo(CUser *this, int id);
int __cdecl CUser::setCharacName(CUser *this, int id, char *src);
int __cdecl CUser::GetSlotIDX(CUser *this);
int __cdecl CUser::isCharacLinkBonusSetting(CUser *this, char flag);
CCharacterView *__cdecl CUser::setCharacLinkBonusSetting(CUser *this, int id, bool a3);
CUser *__cdecl CUser::setCharacLinkMessageFlag(CUser *this, bool a2);
void *__cdecl CUser::SetGuildDBInfo(int id, void *src);
void *__cdecl CUser::ChangeGuildName(CUser *this, char *src);
CUser *__cdecl CUser::SetGuildAgitFlag(CUser *this, bool a2);
void *__cdecl CUser::SetGuildAgitDBInfo(int id, void *src);
CUser *__cdecl CUser::SetGuildCargoCapacity(CUser *this, unsigned int id);
CUser *__cdecl CUser::SetTodayGuildMember(CUser *this, bool a2);
CUser *__cdecl CUser::setHumanCertifyErrorCnt(CUser *this, int id);
CUser *__cdecl CUser::setRestingUserRestrict(CUser *this, bool a2);
CUser *__cdecl CUser::setPunishTradeAlert(CUser *this, __int16 a2);
CUser *__cdecl CUser::setSecuReward(CUser *this, bool a2);
int __cdecl CUser::NeedSecuReward(CUser *this);
CUser *__cdecl CUser::setSecuType(CUser *this, unsigned __int8 a2);
int __cdecl CUser::getRewardType(CUser *this);
CUser *__cdecl CUser::setRewardType(CUser *this, unsigned __int8 a2);
CUser *__cdecl CUser::setSecuGrade(CUser *this, char flag);
char *__cdecl CUser::GetGoldControl(CUser *this);
CUser *__cdecl CUser::setFlagPresentAvengerTitle(CUser *this, bool a2);
CUser *__cdecl CUser::setCheckPickUpRandomOptionItem(CUser *this, bool a2);
CUser *__cdecl CUser::SetCurCharacUsedGiftFatigueQuantity(CUser *this, CUser *user);
CUser *__cdecl CUser::ResetCurCharacUsedGiftFatigueQuantity(CUser *this);
int __cdecl CUser::getHashCode(CUser *this, unsigned __int8 *a2);
int __cdecl CUser::getGmQuestFlag(CUser *this);
__int64 __cdecl CUser::getTotalHackUserTradeGold(CUser *this);
int __cdecl CUser::getTotalHackUserTradeCnt(CUser *this);
CUser *__cdecl CUser::incTradeCount(CUser *this);
int __cdecl CUser::SetTradeSpace(pthread_mutex_t *this, __int16 a2);
int __cdecl CUser::GetGameMasterCharacter(CUser *this);
bool __cdecl CUser::GetDailyBadge(CUser *this, __int16 *a2);
int __cdecl CUser::GetDailyBadge(int id, int value);
int __cdecl CUser::AddDailyBadge(int id, int value);
long double __cdecl CUser::GetRating(CUser *this);
CUser *__cdecl CUser::UpdateRating(CUser *this, float a2);
CUser *__cdecl CUser::set_public_ip_address(CUser *this, int id);
CUser *__cdecl CUser::backupSeed(CUser *this);
CUser *__cdecl CUser::SetPowerUp(CUser *this, bool a2);
CUser *__cdecl CUser::setBreakAwayDungeonClear(CUser *this, bool a2);
CUser *__cdecl CUser::subBreakAwayDungeonClearCnt(CUser *this);
int __cdecl CUser::IsReturnUser(CUser *this);
int __cdecl CUser::getAddExpRateFromPremium(int id, unsigned int value);
int __cdecl CUser::SetPartyIndex(pthread_mutex_t *this, __int16 a2);
int __cdecl CUser::IsTodayGuildMember(CUser *this);
CUser *__cdecl CUser::resetDungeonClearHackCheck(CUser *this);
int __cdecl CUser::IsUsedCoinInDungeon(CUser *this);
int __cdecl CUser::IsDeleteEventDungeonInvitation(CUser *this);
int __cdecl CUser::getCheckPickUpRandomOptionItem(CUser *this);
int __cdecl CUser::GetUseAPCPotionTime(CUser *this);
int __cdecl CUser::SetPvpIndex(CUser *this, __int16 a2);
int __cdecl CUser::get_guildwar_point_per_pvpplay(CUser *this);
CUser *__cdecl CUser::set_guildwar_point_per_pvpplay(CUser *this, int id);
int __cdecl CUser::getPcRoomAuth(CUser *this);
int __cdecl CUser::IsPowerUp(CUser *this);
int __cdecl CUser::GetCheckConnInterval(CUser *this);
CUser *__cdecl CUser::SetResumeChecksumTime(CUser *this, int id);
char *__cdecl CUser::GetPremiumInfoW(CUser *this);
bool __cdecl CUser::IsPremiumUser(CUser *this);
int __cdecl CUser::GetLoginTime(CUser *this);
int __cdecl CUser::get_charac_name_by_charac_no(CUser *this, int id);
CUser *__cdecl CUser::incre_check_count(CUser *this);
int __cdecl CUser::get_connect_count(CUser *this);
int __cdecl CUser::isSendMailCertified(CUser *this);
int __cdecl CUser::getHumanCertifyTimerKey(CUser *this);
int __cdecl CUser::IsRecvEvent(CUser *this);
int __cdecl CUser::isARSUserKick(CUser *this);
unsigned __int8 __cdecl CUser::IncrementTradeGold(CUser *this, unsigned int id, int value);
void __cdecl CUser::requestCubePremiumInfoIfContracted(CUser *this);
int __cdecl CUser::OnItemUnlockWaitTimeout(CUser **this);
_BOOL4 __cdecl CUser::CheckItemLock(CUser *this, int id, int value);
_BOOL4 __cdecl CUser::CheckItemLockSlotSpace(CUser *this, unsigned __int16 a2, unsigned __int16 a3);
int __cdecl CUser::IsAbleItemLock(CUser *this, int id, unsigned __int16 a3);
int __cdecl CUser::IsAbleItemUnlock(CUser *this, int id, unsigned __int16 a3);
int __cdecl CUser::IsAbleItemUnlockCancel(CUser *this, unsigned __int16 a2, unsigned __int16 a3);
int __cdecl CUser::DoItemLock(CUser **this, int id, int value);
int __cdecl CUser::DoItemUnlock(CUser **this, int id, int value);
int __cdecl CUser::DoItemUnlockCancel(CUser **this, int id, int value);
int __cdecl CUser::Redeem_Item(CUser **this, int id);
int __cdecl CUser::Add_RedeemInfo(CUser **this, const Inven_Item *item, int id, bool a4);
void __cdecl CUser::RewardTutorial(CUser *this, unsigned int id);
CUser *__cdecl CUser::set_area(CUser *this, int id);
int __cdecl CUser::Parsing(CUser *this, char *a2);
int __cdecl CUser::Recv(pthread_mutex_t *this);
int __cdecl CUser::AntibotSend(CUser *this, PacketBuf *a2);
int __cdecl CUser::Send(CUser *this, PacketGuard *a2);
int __cdecl CUser::SendClientCrashDownLogToLogDB(CUser *this, int src);
void __cdecl CUser::prepareDisconnect(CUser *this);
int __cdecl CUser::DisConnSig(pthread_mutex_t *a1, int src, char flag, int id);
int __cdecl CUser::InitOnAccept(CUser *this, int id);
unsigned __int16 *__cdecl CUser::GenerateCleanPadVeriData(CUser *this, unsigned __int16 *a2, unsigned __int8 *a3, unsigned __int16 *a4);
_BOOL4 __cdecl CUser::VerifyCleanPadVeriData(CUser *this, unsigned int id);
CUser *__cdecl CUser::setDungeonClearHackCheck(CUser *this, bool a2);
_BOOL4 __cdecl CUser::isDungeonClearHackCheck(CUser *this);
int __cdecl CUser::set_acc_info(CUser *this, unsigned int id, char *s);
void __cdecl CUser::SetCharacInfo(CUser *this, int id, char *a3);
int __cdecl CUser::CreateCharac(CUser *user, int id);
CLevelRewardTableMgr *__cdecl CUser::_onCreateCharacter(CUser *this, unsigned int id, char *a3, char flag);
CLevelRewardTableMgr *__cdecl CUser::_processUnlimitChallenge(CUser *this, unsigned int id, char flag);
CCharacterView *__cdecl CUser::DeleteCharac(CUser *this, unsigned int id);
_BOOL4 __cdecl CUser::CheckDeleteCharacTime(CUser *this, int id);
int __cdecl CUser::GetGuildIdBeforeDeleteCharacter(CUser *this, int id);
int __cdecl CUser::GetServerGroupToPvP(CUser *this);
int __cdecl CUser::lock4DataLoad(CUser *this);
int __cdecl CUser::unlock4DataLoad(CUser *this);
int __cdecl CUser::isLocked4DataLoad(CUser *this);
int __cdecl CUser::lockDeleteCharac(CUser *this);
int __cdecl CUser::unlockDeleteCharac(CUser *this);
int __cdecl CUser::isLockedDeleteCharac(CUser *this);
int __cdecl CUser::lockCreateCharac(CUser *this);
int __cdecl CUser::unlockCreateCharac(CUser *this);
int __cdecl CUser::isLockedCreateCharac(CUser *this);
_BOOL4 __cdecl CUser::checkSelectCharac(CUser *this, int id);
int __cdecl CUser::setCharacInfoDetail(CUser *this, int id, int value, CHARAC_DATA *a4);
int __cdecl CUser::GetCharacInfo(CUser *this, SIG_LOAD_CHARAC *a2);
int __cdecl CUser::getCharacInfoDetail(CUser *this, int id, unsigned int value, CHARAC_DATA *a4);
int __cdecl CUser::CacheCharacterMemory(CUser *this);
int __cdecl CUser::LogoutCachedCharacter(CUser *this, unsigned __int8 a2);
int __cdecl CUser::SelectCharac(CUser *this, int id, int value);
int __cdecl CUser::SetInventory(CUser *this, SIG_LOAD_INVENTORY *a2);
int __cdecl CUser::GetInventoryInfo(CUser *this, SIG_LOAD_INVENTORY *a2);
int __cdecl CUser::GetInventory(CUser *this, SIG_LOAD_INVENTORY *a2);
int __cdecl CUser::IsRestrictedGoods(CUser *this, int id);
unsigned __int8 CUser::RemoveRestrictedGoods(CUser *this, ...);
void __cdecl CUser::SendRestrictedGoods(CUser *this, bool a2, int id);
int __cdecl CUser::SetSkill(CUser *this, SIG_LOAD_SKILL *a2, SIG_COMBO_SKILL *a3);
int __cdecl CUser::GetSkill(CUser *this, SIG_LOAD_SKILL *a2, SIG_COMBO_SKILL *a3);
int __cdecl CUser::GetDungeonClear(CUserCharacInfo *charac_info, int id); // idb
int __cdecl CUser::SetPvpRecord(CUser *this, PvpResultType *a2);
int __cdecl CUser::get_charac_idx(CUser *this, unsigned int id);
int __cdecl CUser::get_charac_no(CUser *this, int id);
int __cdecl CUser::get_character_job(CUser *this, unsigned int id);
int __cdecl CUser::getCurCharacInvenCheckSum(CUser *this);
int __cdecl CUser::getCurCharacSkillCheckSum(CUser *this);
void __cdecl CUser::CUser(CUser *this);
int __cdecl CUser::gainCurCharacFatigue(CUser *this, int id);
char __cdecl CUser::saveTaxMoneyForUpperMember(CUser *this, int id);
unsigned __int8 __cdecl CUser::reset_tag_info_to_me(CUser *this, unsigned int id);
int __cdecl CUser::gainExpAsUpperMember(CUser *this, int id);
int __cdecl CUser::IsGuildSkillLearn(CUser *this, int id);
int __cdecl CUser::gainGuildSkillExp(CUser *this, int id);
int CUser::gainPowerWarRewardExp();
int __cdecl CUser::CheckLimitMiniumAge(CUser *this, unsigned int id, int *a3);
int __cdecl CUser::UseWinPoint(CUser **a1, int id, int value);
void __cdecl CUser::gainWinPoint(CUser **a1, int id, int value);
int __cdecl CUser::_GetSaveInvenBase(CUserCharacInfo *charac_info, int *a2);
int __cdecl CUser::SaveInventory(CUser *this);
int __cdecl CUser::SaveInventoryOnly(CUser *this);
int __cdecl CUser::SaveMoneyCoin(CUser *this);
void __cdecl CUser::SaveMileage(CUser *this);
void __cdecl CUser::LoadMileage(CUser *this);
void __cdecl CUser::SendCashData(CUser *this, bool a2);
void __cdecl CUser::AddMileage(CUser *user, int id, int value);
CUser *__cdecl CUser::SetMileage(CUser *this, int id);
void __cdecl CUser::UseMileage(CUser *this, int id);
int __cdecl CUser::GetMileage(CUser *this);
void __cdecl CUser::_SaveCharacData(CUser *this);
char __cdecl CUser::updateCharacViewVisibleData(CUserCharacInfo *charac_info, int *a2, int id);
char __cdecl CUser::UpdateCurCharacVisibleToCharacViewMemory(CUser *this);
void __cdecl CUser::UpdateCharacView(CUser *this);
CCharacterView *__cdecl CUser::ChangeCharacSlot(CUser *this, unsigned int id, unsigned int value);
int __cdecl CUser::UpdateBloodRecord(CUser *this);
void __cdecl CUser::UpdateDimensionInout(CUser *this);
void __cdecl CUser::UpdateBreakAwayLuckPoint(CUser *this);
void __cdecl CUser::UpdateBreakAwayDungeonClearCnt(CUser *this);
void __cdecl CUser::UpdateCharacLinkBonus(CUser *user, int id, int value, int src, int count);
void __cdecl CUser::saveCharacLinkMessageFlag(CUser *this, bool a2);
void __cdecl CUser::sendCharacLinkMessage(CUser *this);
void __cdecl CUser::decideCharacLinkMessage(CUser *this);
int __cdecl CUser::decideLinkCharacSlotIndexes(CUser *this, char flag, int id);
int __cdecl CUser::checkCharacLinkType(CUser *this, char flag, int id);
void __cdecl CUser::doLinkCharacDisconnect(CUser *this);
void CUser::_updateNPCRelationship();
void __cdecl CUser::_updateSaveOption(CUser *this);
char __cdecl CUser::WorkPerFiveMin(CUser *this);
char __cdecl CUser::WorkPerTenMin(CUser *this);
char __cdecl CUser::UpdateData(CUser *this);
char *__cdecl CUser::get_skill_command_buf(CUser *this);
char __cdecl CUser::get_skill_command_buf(CUser *this, STSkillCommandData::STCommand *a2);
void *__cdecl CUser::setSkillCommandData(CUser *this, char *src);
int __cdecl CUser::findSkillCommandData(CUser *this, int id, STSkillCommandData *a3);
int __cdecl CUser::findSkillCommandData(CUser *this, int id, STSkillCommandData *a3);
int __cdecl CUser::customizingSkillCommand(CUser *this, STSkillCommandData *a2);
int __cdecl CUser::defaultSkillCommand(CUser *this);
int __cdecl CUser::GetParty(CUser *this);
int __cdecl CUser::GetPVPRoom(CUser *this);
int __cdecl CUser::GetWarRoom(CUser *this);
int __cdecl CUser::getBossTower(CUser *this);
int __cdecl CUser::getAdvanceAltar(CUser *this);
int __cdecl CUser::getDeathTower(CUser *this);
int __cdecl CUser::getBlueMarble(CUser *this);
void __cdecl CUser::UpdateLogout(CUser **this, bool a2);
int __cdecl CUser::FatigueUp(CUser *this, unsigned int id);
bool __cdecl CUser::CheckFatigue(CUser *this);
void __cdecl CUser::SendFatigue(CUser *this);
int __cdecl CUser::GetSpecialLevelCharacCnt(CUser *this, int id);
void __cdecl CUser::SendCoin(CUser *this);
void __cdecl CUser::SendOpenflag(CUser *this);
void __cdecl CUser::SendRevengeDungeon(CUser *this);
char __cdecl CUser::DimensionInoutUpdate(CUser *this, bool a2, bool a3);
void __cdecl CUser::AddDailyItem(CUser *this);
void __cdecl CUser::resetDailyData(CUser *this);
void __cdecl CUser::ResetDailyQuest(CUser *this);
void __cdecl CUser::ResetTrainingQuest(CUser *this);
int __cdecl CUser::getCurCharacTotalFatigue(CUser *this);
int __cdecl CUser::getCurCharacTotalMaxFatigue(CUser *this);
int __cdecl CUser::recover_stamina(CUser *this);
int __cdecl CUser::serviceOfShusia(CUser *this);
char __cdecl CUser::RecoverFatigue(CUser *this, __int16 a2);
char __cdecl CUser::RecoverCoin(CUser *this, unsigned int CoinNoPerDay);
CUser *__cdecl CUser::reset(CUser *this);
CUser *__cdecl CUser::log_out(CUser *this);
CUser *__cdecl CUser::checkLogOutCorrectly(CUser *this);
void __cdecl CUser::UpdateCoolTimeItemInfo(CUser *this, unsigned int id);
void __cdecl CUser::UpdateEffectItemInfo(CUser *this, unsigned int id);
_BOOL4 __cdecl CUser::LoadCoolTimeItemInfo(CUser *this, CONTINUOUS_ITEM_INFO *a2);
_BOOL4 __cdecl CUser::LoadEffectItemInfo(CUser *this, CONTINUOUS_ITEM_INFO *a2);
int __cdecl CUser::SendCoolTimeItemInfo(CUser *this, unsigned int id);
int __cdecl CUser::SendEffectItemInfo(CUser *this, unsigned int id);
int __cdecl CUser::_processCharacterDayEvent(CUser *this, unsigned int id, unsigned int value);
int __cdecl CUser::_processFatigueBuffEvent(CUser *this, unsigned int id, unsigned int value);
char __cdecl CUser::_processSpeicalContinuousTimeItem(CUser *this, unsigned int id);
int __cdecl CUser::make_charac_stat(CUser *this, PacketBuf **a2);
_BOOL4 __cdecl CUser::IsPermissionPrivateStore(CUser *this);
CUserCharacInfo *__cdecl CUser::add_pvp_result(CUser **this, bool a2, unsigned int *a3);
void __cdecl CUser::add_guild_pvp_result(CUser *this, int id);
void __cdecl CUser::add_inventory_item(CUser *this, unsigned int id);
void __cdecl CUser::add_guild_point_item(CUser *this);
CUser *__cdecl CUser::SetGuildInfoProxy(CUser *this, STGuildProxy *src);
void __cdecl CUser::send_pvp_record(CUser *this);
_BOOL4 CUser::find_pvp_masterid_walkingout_me(CUser *this, ...);
int CUser::insert_pvp_masterid_walkingout_me(CUser *this, ...);
int __cdecl CUser::reset_pvp_masterid_walkingout_me(CUser *this);
int __cdecl CUser::update_pvp_rank(CUser *this, const PvpResultType *a2);
int __cdecl CUser::update_old_pvp_point(CUser *this);
int __cdecl CUser::update_pvp_point(CUser *this, int id);
char *__cdecl CUser::add_pvp_play_info(CUser *this, unsigned int id, unsigned int value);
void *__cdecl CUser::SetEquipment(CUser *this, int id, char *src, size_t n, _DWORD *a5);
int __cdecl CUser::send_itemspace(CUser *this, int id);
int __cdecl CUser::use_stackable(CUser *this, __int16 a2, CStackableItem *a3, int id, int value);
_BOOL4 __cdecl CUser::CheckCoolTimeItem(CUser *this, unsigned int id);
char __cdecl CUser::_processContinuousItem(CUser *this, unsigned int id, CStackableItem *a3);
void __cdecl CUser::_processCoolTimeItem(CUser *this, CStackableItem *a2, unsigned int id, unsigned int value);
void __cdecl CUser::_processEffectItem(CUser *this, CStackableItem *a2, unsigned int id, unsigned int value);
void __cdecl CUser::use_equipment(CUser *this, int id);
int __cdecl CUser::send_RedeemInfo(CUser *this);
int __cdecl CUser::send_MissionList(CUser *this);
char __cdecl CUser::UpdateMissionCondition(CUser *user, _DWORD *a2, int id);
char __cdecl CUser::ClearMission(CUser *this, __int16 a2);
char __cdecl CUser::ResetMissionList(CUser *this);
char __cdecl CUser::ClearMissionKind(CUser *this, __int16 a2);
int __cdecl CUser::get_pvp_WinningRate_relateMission(CUser *this);
int __cdecl CUser::has_within_Mission(CUser *this);
int __cdecl CUser::acceptable_within_mission(CUser *this);
int __cdecl CUser::is_clear_stealingSkillMission(CUser *this);
int __cdecl CUser::Update_ComboMission(CUser *this, int id, unsigned __int16 a3);
void *__cdecl CUser::set_skill_slot(CUser *this, char *src, char *a3, size_t n);
int __cdecl CUser::_check_level_up(CUser *user, signed int id, int *a3, _DWORD *a4, int value);
void __cdecl CUser::_onLevelUp(CUser *this);
void __cdecl CUser::processLevelUpEventReward(CUser **this, bool a2);
void CUser::processNPCGiftOnLevelUp();
unsigned int __cdecl CUser::_onChangeGrowType(CUserCharacInfo *charac_info, int id, char flag, int value);
Stream *__cdecl CUser::_onQuestClear(CUser *this, int id);
char __cdecl CUser::eventDeliveryQuestClear(CUserCharacInfo *charac_info, int id, int value, int count, int index, int type, int result);
char __cdecl CUser::eventDeliveryBuyItem(CUser *this, int id, const Inven_Item *item);
void CUser::_onCompoundItem();
_Additioal_info *__cdecl CUser::_update_charac_stat(CUser *this, bool a2);
int __cdecl CUser::adjust_charac_stat(CUser *this);
bool __cdecl CUser::calc_lev_stat(CUser *this, _Additioal_info *a2);
void __cdecl CUser::calc_quest_stat(CUser *this, _Additioal_info *a2);
bool __cdecl CUser::complete_reward_list(int id, _DWORD *a2, _DWORD *a3);
int __cdecl CUser::_fnStatQuestClear(CUser *this, char *a2);
_DWORD *__cdecl CUser::add_matched_list(_DWORD *a1, int id, int value);
bool __cdecl CUser::count_specific_items(CUserCharacInfo *charac_info, _DWORD *a2, int id);
char __cdecl CUser::apply_elixir_item(int id, int value, int count);
bool __cdecl CUser::givePvPSkillTree(CUser *this, int id, char flag, int value);
char __cdecl CUser::_postQuestTriggerItem(CUser *this, std::string *a2);
void __cdecl CUser::UseQuestItem(CUser *this, int id);
int __cdecl CUser::gain_sp(CUser *this, int id);
void __cdecl CUser::gain_sfp(CUser *this, int id);
char __cdecl CUser::history_log_sp(CUser **a1, int id, int value, int count);
char __cdecl CUser::history_log_sfp(CUser **a1, int id, int value, int count);
_BOOL4 __cdecl CUser::CheckMoney(CUser *this, int id);
int __cdecl CUser::get_skill_count(CUser *this);
void __cdecl CUser::master_new_skill(FILE **a1, _BYTE *a2);
void __cdecl CUser::init_skill_tree(CUserCharacInfo *charac_info, int id);
char __cdecl CUser::set_charac_guildkey_in_login(CUser *this, unsigned int id, unsigned int value);
void *__cdecl CUser::resetGuildDBInfo(CUser *this);
_BOOL4 __cdecl CUser::IsCompleteGuildFund(CUser *this);
int __cdecl CUser::IsAddableGuildFund(CUser *this, int id);
int __cdecl CUser::CheckGuildLevelUp(CUser *this, unsigned int *a2);
int __cdecl CUser::IsSubGuildMaster(CUser *this);
void __cdecl CUser::send_skill_info(CUser *this);
int __cdecl CUser::CheckQuestMap(CUser *this, int id);
bool __cdecl CUser::CheckQuestMonster(CUserCharacInfo *charac_info, int id, int value, int count);
int __cdecl CUser::CheckDungeonClear(CUser *this, int id);
void __cdecl CUser::SendHasNoGoWithApcQuestInParty(CUser *this, const Quest *a2);
int __cdecl CUser::compute_level_penalty(CUser *this, int id);
unsigned int __cdecl CUser::compute_quest_basic_reward_exp(CUser *this, Quest *a2);
int __cdecl CUser::compute_quest_basic_reward_gold(CUser *this, Quest *a2);
void __cdecl CUser::quest_basic_reward(CUser *this, Quest *a2, int *a3, int *a4, int *a5, int *a6, bool a7);
char *__cdecl CUser::getUserQuestRewardItem(CUser *this, const Quest *a2);
CItem *__cdecl CUser::_GetRecipeItem(CUser *this, unsigned int id, bool a3, int *a4);
_BOOL4 __cdecl CUser::_CheckCompoundSkill(CUser *this, const CStackableItem *a2, bool a3);
int __cdecl CUser::_ProcCompoundCore(CUserCharacInfo *charac_info, _DWORD *a2, int *a3, int id, int value, char flag, PacketBuf **a7, _BYTE *a8, unsigned __int16 a9, int count, int index, CItem *a12, Inven_Item *item);
int __cdecl CUser::copyItemOption(CUser *this, Inven_Item *item, Inven_Item *item);
_BOOL4 __cdecl CUser::isSuccessCompound(CUser *this, int id);
bool __cdecl CUser::_CalcItemVectorMultiply(int id, _DWORD *a2, int value);
int __cdecl CUser::_IsCompoundResult2MoreEquip(int id, _DWORD *a2);
void __cdecl CUser::setRecipeEqiupmentOption(CUserCharacInfo *charac_info, Inven_Item *item, int id, int value, int count, CItem *a6, int index);
int __cdecl CUser::IsOldLotteryItem(CUser *this, unsigned int id);
int __cdecl CUser::lottery_item(CUser **this, int id);
int __cdecl CUser::multibox_lottery_item(CUser **this, int id, int value);
int __cdecl CUser::process_use_locked_multibox(CUserCharacInfo *charac_info, int id, int value, int count); // idb
int __cdecl CUser::process_use_unlocked_multibox(CUserCharacInfo *charac_info, int id, int value, int count); // idb
int __cdecl CUser::check_multibox_error(CUser *this, int id);
int __cdecl CUser::check_locked_multibox_error(CUser *this, const CItem *a2, int id, bool a4);
int __cdecl CUser::check_unlocked_multibox_error(CUser *this, const CItem *a2, int id);
int __cdecl CUser::check_insert_lottery_reward(CUserCharacInfo *charac_info, int id, _DWORD *a3, int value);
int __cdecl CUser::use_multibox_statistic(CUser *this, unsigned int id);
int __cdecl CUser::SendRandomBoxStatistic(char flag, char type);
int __cdecl CUser::update_record(CUser *this, GameResultType *a2);
int __cdecl CUser::GetRentInfo(CUser *this, SIG_LOAD_INVENTORY *a2);
int __cdecl CUser::GetPcRoomRentInfo(CUser *this, SIG_SAVE_PC_ROOM_RENT_ITEM *a2);
int __cdecl CUser::GetDimensionRentInfo(CUser *this, SIG_SAVE_DIMENSION_RENT_ITEM *a2);
char __cdecl CUser::GetInstanceRentalInfo(int id, int value, int count);
bool __cdecl CUser::UpdateCurrentCharacRentalInfo(CUser *this, const InstanceRentalSystem::RentOutput *a2, int id, bool a4);
int __cdecl CUser::DeleteRentalItemInfo(CUser *this, int id);
char __cdecl CUser::DeleteCurrentCharacRentalItemInfo(CUser *this, int id);
int __cdecl CUser::GetCurrentCharacRentalInfo(CUserCharacInfo *charac_info, int *a2, int id);
int __cdecl CUser::checkRentedItem(CUser *this, int id, int value, int count);
int __cdecl CUser::HasCurCharacRentalItem(CUser *this, int id);
int __cdecl CUser::getCurrentCharacRentalInfo(CUserCharacInfo *charac_info, int *a2, int id);
int *__cdecl CUser::setCurrentCharacRentalInfo(CUserCharacInfo *charac_info, int *a2, int id);
int __cdecl CUser::removeRentalItemInfoFromInvenBuf(CUserCharacInfo *charac_info, int id, int value); // idb
int __cdecl CUser::removeRentalItemInfoFromInvenLoadBuf(CUser *this, SIG_LOAD_INVENTORY *a2, int id);
int __cdecl CUser::GetEtcInfo(CUser *this, SIG_LOAD_ETC *a2);
SIG_LOAD_ETC *__cdecl CUser::GetRecord(CUser *this, SIG_LOAD_ETC *a2);
int __cdecl CUser::AddDungeonClear(CUser *this, __int16 a2, int id);
void __cdecl CUser::SendDungeonClearList(CUser *this);
void __cdecl CUser::AddTicket(CUser *this, int id, bool a3);
int __cdecl CUser::GetTicket(int id, int value);
int __cdecl CUser::CheckMoveTown(CUser *this, unsigned int id);
int __cdecl CUser::CheckTicket(CUser *this, int id);
void __cdecl CUser::giveup_panalty(CUser *this);
void __cdecl CUser::set_grow_type(CUser **a1, unsigned __int8 a2, unsigned __int8 a3, InterfacePacketBuf *a4, int id);
void __cdecl CUser::processGrowTypeEvent(CUser *user, unsigned __int8 a2, char flag, int id);
int __cdecl CUser::processAwakenReward(CUser *this, char flag);
int __cdecl CUser::SetGameMasterMode(CUser *this, bool a2);
void __cdecl CUser::makeGuildLevelUpMessage(CUser *this, int id);
void __cdecl CUser::makeGuildSkillMessage(CUser *this, char *a2, int id);
void __cdecl CUser::makeGuildItemUpgradMessage(CUser *this, const char *a2, int id, int value, bool a5);
void __cdecl CUser::makeGuildItemSeparateUpgradMessage(CUser *this, const char *a2, int id, int value, bool a5, int count);
int __cdecl CUser::SetCharacLevel(CUser **this, int id);
int __cdecl CUser::ChangeGrowType_GM(CUser *this, unsigned int id, unsigned int value);
int __cdecl CUser::ClearSkills(CUser *this);
int __cdecl CUser::SetSkillLevel(CUser *this, int id, int value);
int __cdecl CUser::AddItem(CUser *user, unsigned int id, int value, int count, _DWORD *a5, int index);
int __cdecl CUser::SendPacket(CUser *user, int id, PacketGuard *a3); // idb
void __cdecl CUser::SendZeroExpPacket(CUser *this);
int __cdecl CUser::SendCmdPeerErrorPacket(CUser *user, __int16 a2, int id, char flag, PacketBuf **a5);
int __cdecl CUser::SendCmdPeerErrorPacket(CUser *user, __int16 a2, int id, char flag);
int __cdecl CUser::SendCmdOkPacket(CUser *user, __int16 a2);
int __cdecl CUser::SendCmdErrorPacket(CUser *user, __int16 a2, char flag);
int __cdecl CUser::SendCmdErrorPacket(CUser *user, __int16 a2, char flag, PacketBuf **a4);
int __cdecl CUser::SendCmdErrorPacket(CUser *user, __int16 a2, char flag, char type);
int __cdecl CUser::SendCmdErrorPacket2Byte(CUser *user, __int16 a2, __int16 a3);
int __cdecl CUser::SendCmdPacket(CUserCharacInfo *charac_info, int id, int value, char flag);
int __cdecl CUser::SendUpdateItem(CUserCharacInfo *charac_info, int id, int value, int count); // idb
int __cdecl CUser::SendUpdateItemList(CUserCharacInfo *charac_info, int id, int value, unsigned int count);
int __cdecl CUser::IsEquipAvatar(CUser *this);
int __cdecl CUser::SendMoneyFullReason(CUser *user, char flag, int id, int value);
int CUser::LogHistory(CUser *this, char *format, ...);
CUser *__cdecl CUser::setPlayingDungeonIndex(CUser *this, int id);
int __cdecl CUser::getPlayingDungeonIndex(CUser *this);
int __cdecl CUser::getDungeonIdxAfterClear(CUser *this);
CUser *__cdecl CUser::setLastPacketID(CUser *this, int id);
int __cdecl CUser::getLastPacketID(CUser *this);
char __cdecl CUser::ProcPremiumFatigue(CUser *this);
void __cdecl CUser::_UpdateUserInfo4Guild(CUser *this);
bool __cdecl CUser::SetNeedCheckOverEquipItem(CUser *this);
int __cdecl CUser::_isMatchedItem(int id, int value, _DWORD *a3);
void __cdecl CUser::_deleteSpecificItemInven(CUserCharacInfo *charac_info, int id, _DWORD *a3, int value, int count, int index);
void __cdecl CUser::_deleteSpecificItemCargo(CUserCharacInfo *charac_info, _DWORD *a2, int id);
int __cdecl CUser::_deleteSpecificRedeemItem(int id, _DWORD *a2);
CAccountCargo *__cdecl CUser::SetAccountCargoDBData(CUser *this, Inven_Item *src, unsigned int id, unsigned int value);
void __cdecl CUser::_deleteSpecificItemAccountCargo(CUser *user, _DWORD *a2, int id);
void __cdecl CUser::_deleteSpecificItemTitieBook(int id, _DWORD *a2);
char __cdecl CUser::deleteSpecificItem(WongWork::CMailBox **a1, _DWORD *a2, int id);
void __cdecl CUser::processDelDailyItem(CUser *this);
bool __cdecl CUser::deleteDailyStackableItem(CUserCharacInfo *charac_info, int id, int value, int count);
void __cdecl CUser::deleteGuildExpBook(WongWork::CMailBox **this);
int __cdecl CUser::checkCodeChecksumRange(CUser *this, const CodeHackChecksumEx *a2, const CodeHackCheckRangeEx *a3);
int __cdecl CUser::checkCodeChecksum(CUser *this, const CodeHackChecksum *s2, char *dest);
int __cdecl CUser::getSex(CUser *this);
_BOOL4 __cdecl CUser::IsOverBirthDay(CUser *this);
CUser *__cdecl CUser::SetBirth(CUser *this, const char *a2);
int __cdecl CUser::is_fighting(CUser *this);
char __cdecl CUser::set_state(CUserCharacInfo *charac_info, int id);
char __cdecl CUser::printBlackList(CUser *this);
int __cdecl CUser::registerToBlackList(CUser *this, unsigned int id);
int __cdecl CUser::deleteToBlackList(CUser *this, unsigned int id);
int __cdecl CUser::isBlackUser(CUser *this, unsigned int id);
char __cdecl CUser::resetBlackList(CUser *this);
int __cdecl CUser::GetBlackListCount(CUserCharacInfo *charac_info, int id); // idb
int __cdecl CUser::StartRecvEventWaiting(CUser *this);
int __cdecl CUser::reqHumanCertify(CUser **this);
int __cdecl CUser::checkHumanCertify(CUser *this, size_t n, unsigned __int16 *s1);
void *__cdecl CUser::resetHumanCertifyData(CUser *this);
void __cdecl CUser::setHackUser(CUser *this, char *a2, unsigned int id, unsigned int value, unsigned int count, unsigned __int16 a6, int index);
void __cdecl CUser::gainMoneyFromHackUser(CUser *this, unsigned int id, unsigned __int64 a3, unsigned int value, unsigned __int64 a5);
int __cdecl CUser::onUpdateHackCount(CUser *user, unsigned int id, unsigned int value, unsigned int count, unsigned int index); // idb
CUser *__cdecl CUser::onSelectCharacter(CUser *this);
int __cdecl CUser::onDungeonClear(CUser *this, int id);
int __cdecl CUser::reqHumanCertify4ClearMap(CUser *this, bool a2);
CParty *__cdecl CUser::GetUserListByParty(CUser *user, int id);
void __cdecl CUser::sendBackSecurityAuthRequest(CUser *this);
int __cdecl CUser::AuctionPreCheck(CUser *user, __int16 a2, int id);
void __cdecl CUser::discard_mouse_register(CUser *this);
char *__cdecl CUser::GetCurCharacInventoryRef(CUser *this, unsigned __int16 a2, unsigned __int16 a3);
char *__cdecl CUser::GetCurCharacInventoryRef(CUser *this, unsigned __int16 a2, unsigned __int16 a3);
int __cdecl CUser::isEnableAvatarSocketAction(CUser *this);
int __cdecl CUser::isEnableGiveGiftToNPC(CUser *this);
void CUser::resetNPCRelationShipDailyData();
void CUser::sendNPCRelationShipFavor();
int __cdecl CUser::addAvatarItem(CUserCharacInfo *charac_info, int id, char flag, char type, char *src, int value);
char __cdecl CUser::OnRestrictTrade(CUser *this);
char __cdecl CUser::OnPunishUser(CUser *this);
int __cdecl CUser::get_area(CUser *this, bool a2);
unsigned __int8 __cdecl CUser::SaveBackupSkillInfo(CUserCharacInfo *charac_info, void *src, int id);
int __cdecl CUser::SendLoginToPCRoomServer(CUser *this);
int __cdecl CUser::SendLogoutToPCRoomServer(CUser *this);
void __cdecl CUser::SendProperDungeonClearCount(CUser *this);
void __cdecl CUser::SendConditionEventInfo(CUser *this);
void __cdecl CUser::_saveConditionEventInfo(CUser *this, unsigned int id, __int16 a3, __int16 a4);
void __cdecl CUser::_saveProperDungeonClearCount(CUser *this, unsigned int id, __int16 a3);
int __cdecl CUser::InsertOnTimeEventReward(CUser *this, unsigned int id, unsigned int value);
int __cdecl CUser::getCompoundUpgrade(int id, CItem *a2, int value);
void __cdecl CUser::SendUnlimitChallengePacket(CUser *this);
int __cdecl CUser::_processLevelReward(CUser *this, unsigned int id, unsigned int value, char flag);
int __cdecl CUser::AddSecuRewardItem(CUser *this, int id);
int __cdecl CUser::sendSecuRewardItem(CUserCharacInfo *charac_info, int id, int value, int count); // idb
int __cdecl CUser::GetPowerWarPartyVictory(CUser *this);
char *__cdecl CUser::GetSecretShopData(CUser *this);
CUser **__cdecl CUser::GetUserSecretShop(CUser *this);
void __cdecl CUser::SendSecretShopItemList(CUser *this);
int __cdecl CUser::GetUserPosInParty(CUser *this);
_BOOL4 __cdecl CUser::isSecurityServiceUsed(CUser *this);
void __cdecl CUser::SendNotiPacketMessage(CUser *user, char *s, char flag);
_BOOL4 __cdecl CUser::isDuplicationMessage(std::string *this, std::string *a2);
void __cdecl CUser::SetLimitInfo(int id, _DWORD *a2);
int __cdecl CUser::UseLimitItem(CUser *this, int id, bool a3);
_BOOL4 __cdecl CUser::IsLimitItemUsable(CUser *this, int id);
int __cdecl CUser::GetItemLimitInfo(CUser *this, int id);
void __cdecl CUser::GetLimitItemUsage(CUser *this, SIG_LOAD_ETC *a2);
void __cdecl CUser::SendLimitItemUsageNotiInfo(CUser *this, int id, int value, int count);
bool __cdecl CUser::ResetItemByScript(int id, int value);
bool __cdecl CUser::RefillItemByScript(CUserCharacInfo *charac_info, int id);
int __cdecl CUser::AddDBLogItem(int id, int value, int count, int index);
bool __cdecl CUser::DBUpdateDBLogItem(CUser *this);
char __cdecl CUser::EventDungeonClearReward(CUserCharacInfo *charac_info, _DWORD *a2);
CUser *__cdecl CUser::SetTradePunishOverThirtyDays(CUser *this, bool a2);
int __cdecl CUser::isTradePunishOverThirtyDays(CUser *this);
CUser *__cdecl CUser::SetTradePunishType(CUser *this, int id);
int __cdecl CUser::DelTradePunishType(CUser *this, int id);
_BOOL4 __cdecl CUser::isTradePunishType(CUser *this, int id);
int __cdecl CUser::GetTradePunishType(CUser *this);
void __cdecl CUser::SendEventBringUpInfo(CUser *this);
void __cdecl CUser::ReCalcChattingEmoticon(CUser *this);
void __cdecl CUser::SendChattingEmoticon(CUser *this);
_BOOL4 __cdecl CUser::CalLevelUpItemCheck(CUser *this, unsigned int id);
int __cdecl CUser::CalLevelUpItemState(CUser *this, char *a2, int *a3, int id, int value);
void *__cdecl CUser::SendMail(CUser *this, bool a2);
void *__cdecl CUser::SendMultiMail(CUser *this, bool a2);
void *__cdecl CUser::set_MailMsgData(int id, void *src);
void *__cdecl CUser::set_MultimailMsgData(int id, void *src);
int __cdecl CUser::reqSendMailCertify(CUser *this);
char __cdecl CUser::SendEventJarOutputItemStatistics(int id, _DWORD *a2);
void __cdecl CUser::SendCeraShopGiftStatisticLog(CUser *this, unsigned int id, unsigned int value, unsigned int count, unsigned int index);
int CUser::CheckMaxLuckyLevel();
void __cdecl CUser::sendReturnUserFirstLogin(CUser *this);
int __cdecl CUser::UpdateEquipslotFlag(CUser *this, char flag);
void __cdecl CUser::SendOneADayItemShopIndex(CUser *user, _DWORD *a2);
void __cdecl CUser::sendCharacQp(CUser *this);
CQuestShop *__cdecl CUser::incQuestPoint(CUser **this, int id, int value, bool a4);
void __cdecl CUser::setQuestPoint(CUser *this, int id);
int __cdecl CUser::getQuestPoint(CUser *this);
CQuestShop *__cdecl CUser::clearInitQuestPoint(CUser *this);
CQuestShop *__cdecl CUser::incInitQuestPoint(CUser *this, int id);
bool __cdecl CUser::setInitQuestPoint(CUser *this);
void __cdecl CUser::sendCharacQuestPiece(CUser *this);
void __cdecl CUser::incQuestPiece(CUser *this, int id, int value, bool a4);
CQuestShop *__cdecl CUser::clearQuestPiece(CUser *this);
CItemMakingSkill *__cdecl CUser::SendItemMakingSkillInfo(CUser *this);
void __cdecl CUser::send_clear_quest_list(CUser *this);
int __cdecl CUser::getInDungeonItemSellCount(CUser *this, unsigned __int16 a2, unsigned __int16 a3);
CUser *__cdecl CUser::setCharacSlotCountInfo(CUser *this, unsigned __int8 a2, unsigned __int8 a3);
int CUser::getCharacSlotCountDefaultInfo();
int __cdecl CUser::VerifyPresentAvengerTitle(CUser *this);
int __cdecl CUser::getBeforeAreaTime(CUser *this);
CUser *__cdecl CUser::setBeforeAreaTime(CUser *this, int id);
void __cdecl CUser::CalculateExpertJobMaterials(CUserCharacInfo *charac_info, _DWORD *a2);
int __cdecl CUser::GetCurExpertJobLevel(CUser *this, unsigned int id);
int __cdecl CUser::select_charac_set_visible_values(CUser *this, char flag);
void __cdecl CUser::send_charac_visible_data(CUser *this);
int __cdecl CUser::send_ontime_reward_start_notify(CUser *this);
int __cdecl CUser::delete_ontime_reward_list(CUser *this);
int __cdecl CUser::is_recipe_items_avatar_type(int id, _DWORD *a2);
bool __cdecl CUser::verifyDoingQuest(CUser *this);
void __cdecl CUser::send_broadcast_lottery_gold_message(CUser *this, unsigned int id, int value);
int __cdecl CUser::set_server_fatigue_count(CUser *this, __int16 a2);
int __cdecl CUser::get_server_fatigue_count(CUser *this, unsigned __int8 a2);
int __cdecl CUser::reset_server_fatigue_data(CUser *this);
CUser *__cdecl CUser::set_fatigue_count_db(CUser *this, char flag, char type);
int __cdecl CUser::get_fatigue_count_db(CUser *this, int id);
char *__cdecl CUser::get_ingame_event_history(CUser *this);
char *__cdecl CUser::get_ingame_event_history_update(CUser *this);
char __cdecl CUser::get_ingame_event_history(int id, int value, _DWORD *a3);
_BYTE *__cdecl CUser::set_ingame_event_history(CUser *this, int id, int value, int count);
void __cdecl CUser::set_ingame_event_history(CUser *user, int id);
int __cdecl CUser::reset_ingame_event_history(CUser *this);
int __cdecl CUser::reset_ingame_event_history_update(CUser *this);
CUser *__cdecl CUser::decide_growth_power_reward_system(CUser *this);
CUser *__cdecl CUser::set_growth_power_exp_reward(CUser *this, int id);
CUser *__stdcall CUser::get_growth_power_exp_reward(CUser *this, int id);
_BOOL4 __cdecl CUser::alonePlay_Mode(CUser *this);
_BOOL4 __cdecl CUser::alonePlay_Mode(CUser *user, int id);
CUser *__cdecl CUser::setUseCraneStart(CUser *this, bool a2);
int __cdecl CUser::isUseCraneStart(CUser *this);
int __cdecl CUser::get_SoloPlay_mode(CUser *this);
int __cdecl CUser::get_SoloPlay_msgType(int id, int value);
char __cdecl CUser::GetAuraAvatarOption(CUser *this, stAuraAvatarOption *a2);
void __cdecl CUser::UpdateAuraAvatarOption(CUser *this, unsigned int src, int id);
int __cdecl CUser::get_aura_avatar_option_value(CUser *this, unsigned int id);
void __cdecl CUser::send_aura_avatar_option(CUser *this);
int __cdecl CUser::is_equip_aura_avatar(CUser *this, char flag, int *a3);
void __cdecl CUser::Send_SoloPlay_Reject_NotiPack(CUser *user, char *s, int id, int value);
int __cdecl CUser::SaveMercenaryData(CUser *this);
_BOOL4 __cdecl CUser::SetCharacMercenaryInfo(CUser *this, int id, CHARAC_LOAD_MERCENARY *a3);
char __cdecl CUser::AddCurCharacMercenaryInfo(CUser *this);
_DWORD *__cdecl CUser::RemoveCharacMercenaryInfo(CUser *this, unsigned int id);
int __cdecl CUser::Return_Mercenary_Charac(CUser **this, unsigned int id, competition_reward_result *a3);
_BOOL4 __cdecl CUser::Competition_Mercenary_Charac(CUser **this, unsigned int id, char flag, char type);
bool __cdecl CUser::SetMercenaryInfoPacket(CUser *this, PacketBuf **a2);
bool __cdecl CUser::isCompetitionMercenary(CUser *this);
int __cdecl CUser::CalcMercenaryAvatarBonus(CUser *this);
char __cdecl CUser::setAvatarTypeBonus(CUser *this, unsigned __int8 a2);
bool __cdecl CUser::GetCurCharacOption(CUser *this, CharacterOption *a2);
void __cdecl CUser::sendCharacOption(CUser *this);
int __cdecl CUser::NextCharacMoneyLog(CUser *this, time_t timer);
_DWORD *__cdecl CUser::AddMoneyPlus(CUser *this, int id);
_DWORD *__cdecl CUser::AddMoneyMinus(CUser *this, int id);
_BOOL4 __cdecl CUser::exceptedStateMoneyLog(CUser *this);
CUser *__cdecl CUser::SendMoenyLog(CUser *this);
CUser *__cdecl CUser::SetProperLevelDungeonUser(CUser *this);
CUser *__cdecl CUser::ClearProperLevelDungeonUser(CUser *this);
int __cdecl CUser::IsProperLevelDungeonUser(CUser *this);
void __cdecl CUser::ProcProperLevelDungeonClear(CUser *this);
_BOOL4 __cdecl CUser::verifyStackableItemProcess(CUser *user, int id, CItem *a3);
_BOOL4 __cdecl CUser::verifyStackableItemActionPlace(CUser *user, int id, CItem *a3);
_BOOL4 __cdecl CUser::verifyStackableItemActionPlace(CUser *user, int id, unsigned int value);
CUser *__cdecl CUser::setForceDropFlag(CUser *this, bool a2);
int __cdecl CUser::getForceDropFlag(CUser *this);
void __cdecl CUser::updatePcRoomPlayTime(CUser *this);
CUser *__cdecl CUser::collectPcRoomPlayTime(CUser *this);
CUser *__cdecl CUser::setPcRoomPlayTimeData(CUser *this, unsigned int id, unsigned int value, unsigned __int8 a4);
void __cdecl CUser::sendNotiPcRoomPlayTime(CUser *this);
void *__cdecl CUser::resetInformNoticeFlag(CUser *this);
void __cdecl CUser::loadInformNoticeFlag(CUser *this, char *a2);
CUser *__cdecl CUser::handleInformNoticeFlag(CUser *this, unsigned int id);
_BOOL4 __cdecl CUser::checkInformNoticeFlag(CUser *this, unsigned int id, unsigned int value);
int __cdecl CUser::isSaveInformNoticeFlag(CUser *this);
CUser *__cdecl CUser::enableSaveInformNoticeFlag(CUser *this);
CUser *__cdecl CUser::disableSaveInformNoticeFlag(CUser *this);
int __cdecl CUser::getInformNoticeFlag(CUser *this, int id);
bool __cdecl CUser::getInformNoticeFlagIndex(CUser *user, int *a2);
void __cdecl CUser::sendInformNoticeFlag(CUser *this);
char __cdecl CUser::initAllSkill(CUser *this);
void __cdecl CUser::initTPSkill(CUser *this);
int __cdecl CUser::GetManageLevel(CUser *this);
int __cdecl CUser::GetManagePoint(CUser *this);
int __cdecl CUser::GetUserMaxLevel(CUser *this);
CUser *__cdecl CUser::SetManageLevel(CUser *this, int id);
CUser *__cdecl CUser::SetManagePoint(CUser *this, int id);
CUser *__cdecl CUser::SetUserMaxLevel(CUser *this, int id);
CUser *__cdecl CUser::CalcurateUserMaxLevel(CUser *this);
CUser *__cdecl CUser::CalcurateManagePoint(CUser *this);
_BOOL4 __cdecl CUser::CalcurateManageLevel(CUser *this);
int __cdecl CUser::setTagCharacInfo(CUser *this, int id, unsigned int value, TAG_CHARAC_DATA *a4);
int __cdecl CUser::setTagCharacInven(CUser *this, TAG_CHARAC_INVEN_DATA *src);
void __cdecl CUser::SendTagCharacInfo(CUser *this);
int __cdecl CUser::getTagCharacInfo(CUser *this, int id, unsigned int value, TAG_CHARAC_DATA *a4);
int __cdecl CUser::getTagCharacInventory(CUser *this, TAG_CHARAC_INVEN_DATA *dest);
int __cdecl CUser::MakeTagCharacInfo(CUser *this, PacketBuf **a2);
void __cdecl CUser::SendManageLevelUpNoti(CUser *this);
bool __cdecl CUser::ValidateStrikerInfo(CUser *this);
void __cdecl CUser::sendDecorationObjectCnt(CUser *this, __int16 a2);
void __cdecl CUser::SendEventMailAlaramTooltip(CUser *this);
int __cdecl CUser::setMoveSpace(int id, int value);
int __cdecl CUser::getMoveSpace(CUser *this);
void __cdecl CUser::sendBlueMarbleEnterCount(CUser *this);
void __cdecl CUser::updateBlueMarbleEnterCount(CUser *this);
SIG_ATTENDANCE_EVENT *__cdecl CUser::GetCharacCashAttendanceInfo(CUser *this, SIG_ATTENDANCE_EVENT *a2);
void __cdecl CUser::SendMaxEquipLevel(CUser *this);
void __cdecl CUser::processLevelUpEvent(CUser *this);
int __cdecl CUser::SetBingoData(int id, int value);
char *__cdecl CUser::getBingoData(CUser *this);
void __cdecl CUser::initBingoData(CUser *this);
void __cdecl CUser::sendBingoData(CUser *this);
void __cdecl CUser::sendBingoAddData(CUser *this);
char *__cdecl CUser::updateBingoData(CUser *this);
void __cdecl CUser::giveLotteryCountItem(CUser **this, unsigned int id, bool a3);
void __cdecl CUser::SetGrowthWeaponEventInfo(CUser *user, int id);
char *__cdecl CUser::getGrowthWeaponEventdata(CUser *this);
char __cdecl CUser::SetGrowthCreatureEventInfo(int id, int value);
char *__cdecl CUser::getGrowthCreatureEventdata(CUser *this);
char __cdecl CUser::setCharacLevelUpGift_AccountOnce(int id, int value);
char *__cdecl CUser::getCharacLevelUpGift_AccountOnce(CUser *this);
void CUser::sendEventInfo();
void __cdecl CUser::processReturnUserQuestAutoClear(CUser *this);
void __cdecl CUser::processReturnUser(CUser *this);
int __cdecl CUser::GiveItemsReturnUser(CUser *this);
int __cdecl CUser::GiveEquipItemsReturnUser(CUser *this);
int __cdecl CUser::getReturnUserLevelKey(CUser *this, int id, int value);
void CUser::questAutoClear();
void __cdecl CUser::updateComboSkill(CUser *this);
void __cdecl CUser::sendComboSkillList(CUser *this);
void __cdecl CUser::processFatigueCharac(CUser *this, int id);
int __cdecl CUser::SendCmdErrorPacketJpn(CUser *user, __int16 a2, __int16 a3);
int __cdecl CUser::DoGetGoldItem(CUserCharacInfo *charac_info, int id, int value, char flag, _DWORD *a5);
CUser *__cdecl CUser::SetBuyingGold(CUser *this, bool a2);
int __cdecl CUser::GetBuyingGold(CUser *this);
int __cdecl CUser::DoGetCeraPointItem(int id, int value, char flag, int count, int index);
int __cdecl CUser::GetCeraPoint(CUser *this);
CUser *__cdecl CUser::SetCeraPoint(CUser *this, unsigned int id);
int __cdecl CUser::UseCeraPoint(CUser *this, unsigned int id);
CUser *__cdecl CUser::SetPuUser(CUser *this, bool a2);
int __cdecl CUser::GetPuUser(CUser *this);
void __cdecl CUser::SendAradEventItemLog(CUser *this, int id, int value);
void __cdecl CUser::LoadCharacTypeHotKey(CUser *this, int id, int value);
_BOOL4 __cdecl CUser::CheckLoadHotKeyCashedCharacType(CUser *this, int id, int value);
_BOOL4 __cdecl CUser::GetCharacHotKeyType(CUser *this, int id);
CUser *__cdecl CUser::setComboSkillSet(CUser *this, bool a2);
int __cdecl CUser::isComboSkillSet(CUser *this);
int __cdecl CUser::isAllowLocationGeoState(CUser *this);
CUser *__cdecl CUser::setAllowLocationGeoState(CUser *this, bool a2);
void __cdecl CUser::compoundSystemMessage(CUser *this, const Inven_Item *item);
char __cdecl CUser::compoundGuildMessage(CUser *this, const Inven_Item *item);
CUser *__cdecl CUser::recipeForceProbability(CUser *this, int id);
int __cdecl CUser::getRecipeProbability(CUser *this);
CUser *__cdecl CUser::SetEventCreateDnfReward(CUser *this, bool a2);
int __cdecl CUser::GetEventCreateDnfReward(CUser *this);
void __cdecl CUser::RewardItem2DeleteInvalidItem(CUser **a1, std::string *a2, _DWORD *a3);
void __cdecl CUser::GiveMeBoxReward(CUser *this);
CUser *__cdecl CUser::resetMoneyLog(CUser *this);
int __cdecl CUser::GetFirstLogin(CUser *this);
int __cdecl CUser::isBreakAwayDungeonClear(CUser *this);
CUser *__cdecl CUser::setUsedBreakAwayLuckPoint(CUser *this, bool a2);
int __cdecl CUser::isUsedBreakAwayLuckPoint(CUser *this);
int __cdecl CUser::isJoinedSchoolPointEvent(CUser *this);
CUser *__cdecl CUser::DisableSaveMemberBonusFatigue(CUser *this);
int __cdecl CUser::IsEnableSaveMemberBonusFatigue(CUser *this);
bool __cdecl CUser::ResetCharacExpandData(charac_expand::CData **this);
int __cdecl CUser::ResetDBLogItem(CUser *this);
int __cdecl CUser::get_local_ip_address(CUser *this);
CUser *__cdecl CUser::resetPlayExpAdd(CUser *this);
CUser *__cdecl CUser::incPlayExpAdd(CUser *this, int id);
__int64 __cdecl CUser::incTotalHackUserTradeGold(CUser *this, unsigned __int64 a2);
CUser *__cdecl CUser::incTotalHackUserTradeCnt(CUser *this, unsigned int id);
int __cdecl CUser::GetResumeChecksumTime(CUser *this);
CUser *__cdecl CUser::UpdateTutorialSkipable(CUser *this);
int __cdecl CUser::getAddQuestItemDropRateFromPremium(int id, unsigned int value);
CUser *__cdecl CUser::SetProgLogout(CUser *this);
int __cdecl CUser::getLinkCharacNo(CUser *this, char flag);
int __cdecl CUser::isCharacLinkMessageFlag(CUser *this);
CUser *__cdecl CUser::setLinkCharacDisconnectFlag(CUser *this, bool a2);
int __cdecl CUser::isLinkCharacDisconnectFlag(CUser *this);
int __cdecl CUser::getDisconnectLinkCharacSlotIdx(CUser *this);
CUser *__cdecl CUser::set_before_area(CUser *this, int id);
char *__cdecl CUser::GetGuildName(CUser *this);
int __cdecl CUser::GetGuildLevel(CUser *this);
int __cdecl CUser::isLoadingHackGold(CUser *this);
CUser *__cdecl CUser::setLoadHackGold(CUser *this, bool a2);
int __cdecl CUser::GetETC(CUser *this, __int16 a2);
CUser *__cdecl CUser::ResetUsedCoinInDungeon(CUser *this);
void *__cdecl CUser::ClearItemSellCount(CUser *this);
CUser *__cdecl CUser::setCharacSlotLimit(CUser *this, unsigned __int8 a2);
int __cdecl CUser::getFlagPresentAvengerTitle(CUser *this);
CUser *__cdecl CUser::reset_update_ontime_last_recv_idx(CUser *this);
int __cdecl CUser::is_update_ontime_last_recv_idx(CUser *this);
char *__cdecl CUser::get_server_fatigue_day_data(CUser *this);
int __cdecl CUser::get_server_fatigue_day_size(CUser *this);
CUser *__cdecl CUser::ResetCurCharacUsedFatigueQuantity(CUser *this);
int __cdecl CUser::GetCurCharacUsedFatigueQuantity(CUser *this);
int __cdecl CUser::GetChangedGiftFatigueQuantity(CUser *this);
CUser *__cdecl CUser::SetWarRoomIndex(CUser *this, __int16 a2);
CUser *__cdecl CUser::ResetCoinCount(CUser *this);
int __cdecl CUser::GetUsedCoinCount(CUser *this);
CUser *__cdecl CUser::resetAccountUsedFatigue(CUser *this);
CUser *__cdecl CUser::incChattingMessageCount(CUser *this, int id);
int __cdecl CUser::getChattingMessageCount(CUser *this);
bool __cdecl CUser::ResetDailyCharacExpandDataMidnight(CUser *this);
bool __cdecl CUser::ResetDailyCharacExpandData(CUser *this);
CUser *__cdecl CUser::set_trick_area(CUser *this, int id);
int __cdecl CUser::get_before_area(CUser *this);

#endif // __CUSER_H__
