#ifndef DNF_ITEM_INFO_ORM_H
#define DNF_ITEM_INFO_ORM_H

#include "db_connection_manager.h"

typedef struct {
    int it_no;
    char it_name[121];
    char it_eng_name[121];
    char it_explain[1024];
    signed char master_type;
    short sub_type;
    char job[26];
    signed char class;
    char revert[11];
    signed char level;
    short skill;
    float create_ratio;
    signed char rarity;
    short weight;
    int price;
    short cash;
    short medal;
    short durability;
    short cooltime;
    short hp_max;
    short mp_max;
    short phy_att;
    short phy_def;
    short mag_att;
    short mag_def;
    short equip_phy_att;
    short equip_phy_def;
    short equip_mag_att;
    short equip_mag_def;
    signed char ref_fire;
    signed char ref_water;
    signed char ref_dark;
    signed char ref_light;
    signed char ref_all;
    signed char ref_slow;
    signed char ref_freeze;
    signed char ref_poison;
    signed char ref_stun;
    signed char ref_cus;
    signed char ref_blind;
    signed char ref_lite;
    signed char ref_ston;
    signed char ref_sleep;
    signed char ref_deekement;
    signed char ref_deadlystrike;
    signed char ref_bleeding;
    signed char ref_confuse;
    signed char ref_hold;
    signed char ref_all_stat;
    short ref_pierce;
    short ref_stuck;
    short inven_max;
    short hp_regenrate;
    short mp_regenrate;
    short mov_speed;
    short att_speed;
    short quest;
    short hit_recovery;
    short jump;
    char att_element;
    short att_active_status;
    float att_active_status_ratio;
    short att_active_status_pow;
    short att_backforce;
    short att_upforce;
    signed char att_hp_drain;
    signed char att_mp_drain;
    float criticalhit_rate;
    float stuck_rate;
    signed char att_defenseIgnore;
    char skill_levelup[121];
    char set_type;
    char url[129];
    char jewel_type[6];
    char detail_explain[256];
    char flavor_text[256];
    int anti_evil;
    int value;
    int required_skill;
    char need_material[256];
    int physical_absolute_damage;
    int physical_damage_reduce;
    int physical_absolute_defense;
    int magical_absolute_damage;
    int magical_damage_reduce;
    int magical_absolute_defense;
    int fire_attack;
    int water_attack;
    int dark_attack;
    int light_attack;
    int weapon_break_resistance;
    int armor_break_resistance;
    int all_activestatus_resistance;
    int rigidity;
    char item_aura[256];
    float magical_critical_hit;
    char set_name[256];
    char set_item[256];
    char fullset_basic_explain[256];
    char fullset_detail_explain[1024];
    char parameter_basic_explain[256];
    char parameter_detail_explain[256];
    int part_set_index;
    char skill_data_up[256];
    char hide_equipment[34];
    signed char db_piece_count;
    int set_item_master;
    int it_set_no;
    char ani_variation[1024];
    char ani_variation_expand[1024];
    char ani_variation2[1024];
    char ani_variation_expand2[1024];
    char hide_growtype_avatar[6];
    float room_list_move_speed_rate;
    signed char icon_mark_number;
    char extra_icon_idx_list[9];
    float hp_max_rate;
    float mp_max_rate;
    int all_attack;
} DnfItemInfo;

/* CRUD Operations */
int DnfItemInfo_Add(DBConnectionManager* manager, const DnfItemInfo* record);
int DnfItemInfo_Get(DBConnectionManager* manager, int it_no, int it_set_no, signed char db_piece_count, DnfItemInfo* record);
int DnfItemInfo_Update(DBConnectionManager* manager, const DnfItemInfo* record);
int DnfItemInfo_Delete(DBConnectionManager* manager, int it_no, int it_set_no, signed char db_piece_count);
int DnfItemInfo_Exists(DBConnectionManager* manager, int it_no, int it_set_no, signed char db_piece_count);
int DnfItemInfo_GetAll(DBConnectionManager* manager, DnfItemInfo* records, int max_count, int* actual_count);

#endif /* DNF_ITEM_INFO_ORM_H */