#ifndef CBATTLE_FIELD_H
#define CBATTLE_FIELD_H

#include <common/defs.h>

// CBattle_Field declarations
int __cdecl CBattle_Field::get_dungeon_diff(CBattle_Field *this);
int __cdecl CBattle_Field::GetDungeon(CBattle_Field *this);
int __cdecl CBattle_Field::GetMapInfoKeyValue(CBattle_Field *this, int id, int value);
int __cdecl CBattle_Field::GetCurrentMapInfo(CBattle_Field *this);
int __cdecl CBattle_Field::GetMapInfoFromPos(MazeScript **this, int id, int value, bool a4);
int __cdecl CBattle_Field::IsAssignNPCByPotion(CBattle_Field *this);
int __cdecl CBattle_Field::getMapWidth(CBattle_Field *this);
int __cdecl CBattle_Field::getMapHeight(CBattle_Field *this);
int __cdecl CBattle_Field::getBloodState(CBattle_Field *this);
void *CBattle_Field::GetEnableHellDungeon();
_BYTE *__cdecl CBattle_Field::SetEnableHellDungeon(CBattle_Field *this);
_BOOL4 __cdecl CBattle_Field::check_start_point(CBattle_Field *this);
_BOOL4 __cdecl CBattle_Field::check_end_point(CBattle_Field *this);
int __cdecl CBattle_Field::get_cur_map(CBattle_Field *this);
CBattle_Field *__cdecl CBattle_Field::setUltimateDifficulty(CBattle_Field *this, char flag);
int __cdecl CBattle_Field::getUltimateDifficylty(CBattle_Field *this);
int __cdecl CBattle_Field::GetMapInfo(CBattle_Field *this);
int __cdecl CBattle_Field::getMaze(CBattle_Field *this);
int __cdecl CBattle_Field::GetCurrentMapIndex(CMap **this);
_BOOL4 __cdecl CBattle_Field::IsClearDungeon(CBattle_Field *this);
int __cdecl CBattle_Field::get_dungeon_index(CBattle_Field *this);
CBattle_Field *__cdecl CBattle_Field::SetParty(CBattle_Field *this, CParty *party);
CBattle_Field *__cdecl CBattle_Field::SetCurSeatNo(CBattle_Field *this, int id);
void __cdecl CBattle_Field::CBattle_Field(CBattle_Field *this);
CBattle_Field *__cdecl CBattle_Field::SetTournamentCurRound(CBattle_Field *this, int id);
int __cdecl CBattle_Field::GetTournamentCurRound(CBattle_Field *this);
int __cdecl CBattle_Field::DestroyPassiveObject(CBattle_Field *this, int id);
_BOOL4 __cdecl CBattle_Field::CheckHellPartyCondition(CBattle_Field *this);
int __cdecl CBattle_Field::GetHellPartyDifficulty(CUserCharacInfo ***a1, int id);
int __cdecl CBattle_Field::GetHellPartyEventType(CBattle_Field *this, char flag);
void __cdecl CBattle_Field::SetGridPath(CBattle_Field *this, MazeScript *a2, int id);
int *__cdecl CBattle_Field::getCurPosXY(CBattle_Field *this, int *a2, int *a3);
int *__cdecl CBattle_Field::getLastPosXY(CBattle_Field *this, int *a2, int *a3);
int __cdecl CBattle_Field::getMap(CBattle_Field *this, int id);
CDungeonClearTracer *__cdecl CBattle_Field::setDungeonClearTrace(CBattle_Field *this, int id, int value, int count, int index);
int __cdecl CBattle_Field::getAddChampionMobCnt(CBattle_Field *this);
int __cdecl CBattle_Field::get_monster_list(CBattle_Field *battlefield, int *a2);
char __cdecl CBattle_Field::add_monster_list_bossroom_condition(int *a1, int id, int value, int count);
char __cdecl CBattle_Field::add_monster_hell_party(CBattle_Field *this, map_monster *a2, bool *a3, int *a4, int *a5);
int __cdecl CBattle_Field::add_monster_blood(CBattle_Field *this, map_monster *a2, int *a3, int *a4);
void __cdecl CBattle_Field::add_monster_APC_AI(CMap **this, int *a2);
void __cdecl CBattle_Field::add_monster_APC_AI_by_rate(CDungeon **this, map_monster *s, int *a3, CDungeon *dungeon, CDungeon *dungeon);
bool __cdecl CBattle_Field::add_monster_additional_champion(CBattle_Field *battlefield, _DWORD *a2, int id);
char __cdecl CBattle_Field::add_monster_event(CBattle_Field *this, int *a2, int id, int value);
char __cdecl CBattle_Field::set_monster_ability(CBattle_Field *this);
char __cdecl CBattle_Field::insert_tournamentRoundMonster(CBattle_Field *this);
void __cdecl CBattle_Field::add_item_curr_map(CBattle_Field *this, int *a2, int *a3);
void __cdecl CBattle_Field::ConsistMap(CBattle_Field *this);
int __cdecl CBattle_Field::ConsistTournament(CUser ***a1, int id, int *a3, int value);
_BOOL4 __cdecl CBattle_Field::MakeBasicRoundInfo(int id, int value, _DWORD *a3, int count);
bool __cdecl CBattle_Field::ChoiceFirstGroup(int id, _DWORD *a2, int value);
void __cdecl CBattle_Field::ConsistTournamentRound(int id, _DWORD *a2, _DWORD *a3, int value, int *a5);
_BOOL4 __cdecl CBattle_Field::InsertTournamentInfo(int id, _DWORD *a2, _DWORD *a3, int value);
bool __cdecl CBattle_Field::MakeRoundInfo(int id, int value, int count, int *a4);
void __cdecl CBattle_Field::MakeNextRoundInfo(int id, int value, int count);
bool __cdecl CBattle_Field::MakeTournamentMonsterList(int id, int value, int *a3);
bool __cdecl CBattle_Field::AddTournamentMonster(int id, int value, int count, char flag);
int __cdecl CBattle_Field::add_blood_monster(CMap **a1, map_monster *a2, int *a3, int *a4, _DWORD *a5, _DWORD *a6);
void __cdecl CBattle_Field::BloodSpawnTimerManager(CBattle_Field *this, bool a2, bool a3);
void __cdecl CBattle_Field::checkKilledSpawnBloodMonsters(CBattle_Field *this, int id);
int __cdecl CBattle_Field::BloodPhaseSpawnTimerResgister(CBattle_Field *this, __int16 a2);
void __cdecl CBattle_Field::BloodPhaseSpawn(CMap **this, __int16 a2, __int16 *a3, int id, int value);
void __cdecl CBattle_Field::BloodMonsterSpawnPacket(CBattle_Field *this, int id, int value, __int16 a4);
void __cdecl CBattle_Field::BloodCrazyMonsterSpawnPacket(CBattle_Field *this);
void __cdecl CBattle_Field::BloodRoundMaxTimePacket(CUser ***this, __int16 a2, int id, int value);
void __cdecl CBattle_Field::BloodRoundIntervalPacket(CUser ***this, __int16 a2, int id);
int __cdecl CBattle_Field::forceValuesToChangeRound(CBattle_Field *this, __int16 a2, __int16 a3, int id);
int __cdecl CBattle_Field::getNextRoundRandomDifficulty(CBattle_Field *this);
int __cdecl CBattle_Field::getNextRoundDifficulty(CBattle_Field *this, __int16 a2);
int __cdecl CBattle_Field::getNextSamllRoundOrder(CBattle_Field *this, __int16 a2, int id);
int __cdecl CBattle_Field::get_blood_round_difficylty_of_small_round(CBattle_Field *this, __int16 a2);
void __cdecl CBattle_Field::sendUltimateRandomDifficulty(CUser ***this, char flag, char type, __int16 a4);
void __cdecl CBattle_Field::sendUltimateRandomDifficulty(CUser ***this, char flag, char type);
void __cdecl CBattle_Field::startUltimateRound(CBattle_Field *this);
int __cdecl CBattle_Field::get_blood_round_of_small_round(CBattle_Field *this, __int16 a2);
int __cdecl CBattle_Field::get_blood_spawn_cnt_of_small_round(CBattle_Field *this, __int16 a2);
int __cdecl CBattle_Field::get_blood_spawn_small_round_interval(CBattle_Field *this, __int16 a2);
int __cdecl CBattle_Field::get_blood_spawn_time_of_next_small_round(CBattle_Field *this, __int16 a2);
int __cdecl CBattle_Field::get_blood_spawn_time_of_phase(CBattle_Field *this, __int16 a2);
int __cdecl CBattle_Field::get_blood_spawn_cnt_of_phase(CBattle_Field *this, __int16 a2, __int16 a3);
int __cdecl CBattle_Field::get_blood_spawn_phase_total_cnt_of_small_round(CBattle_Field *this, __int16 a2);
CBattle_Field *__cdecl CBattle_Field::reset_blood_values(CBattle_Field *this);
int __cdecl CBattle_Field::checkBloodSpawnOrder(CBattle_Field *this, __int16 a2);
int __cdecl CBattle_Field::IsFirstEnterDungeon(CBattle_Field *this);
CBattle_Field *__cdecl CBattle_Field::ResetFirstEnterDungeon(CBattle_Field *this);
void __cdecl CBattle_Field::moveMap_1_Log(CBattle_Field *this, int id, int value);
void __cdecl CBattle_Field::moveMap_2_Log(CBattle_Field *this, int id, int value);
void __cdecl CBattle_Field::moveMap_3_Log(CBattle_Field *this, int id, int value);
void __cdecl CBattle_Field::moveMap_4_Log(CBattle_Field *this, int id, int value, const GridScript *a4);
int __cdecl CBattle_Field::check_boss_map(CBattle_Field *this, int id, int value);
int __cdecl CBattle_Field::check_movemap_range(const char **this, int id, int value);
_BOOL4 __cdecl CBattle_Field::is_visited_map(MazeScript **this, int id, int value);
_BOOL4 __cdecl CBattle_Field::is_visited_map_goto(MazeScript **this, int id, int value);
CBattle_Field *__cdecl CBattle_Field::on_not_visited_map(CBattle_Field *this, int id, int value, bool *a4);
int __cdecl CBattle_Field::check_visited_map(CDungeon **this, int id, int value, bool *a4);
int __cdecl CBattle_Field::get_invade_direction(CBattle_Field *this, int id, int value);
void __cdecl CBattle_Field::choose_random_bossmap_from_dummymaps(CBattle_Field *this, const char **a2, const GridScript *a3, int *a4, bool *a5, int id, int value, int count);
int __cdecl CBattle_Field::get_candidator_map(CBattle_Field *battlefield, const char **a2, int *a3, int *a4, _DWORD *a5, int id, int value, int count);
int __cdecl CBattle_Field::set_visited_map(CBattle_Field *this, int id, int value, bool a4);
CBattle_Field *__cdecl CBattle_Field::swap_curpos_xy(CBattle_Field *this, int id, int value);
int __cdecl CBattle_Field::set_map_id(CBattle_Field *battlefield, int id, int *a3, _DWORD *a4);
int __cdecl CBattle_Field::set_visited_map_goto(CBattle_Field *this, int id, int value);
int __cdecl CBattle_Field::MoveMap(MazeScript **this, unsigned int id, unsigned int value, bool *a4);
int CBattle_Field::SetDamagedPacketCnt(CBattle_Field *this, ...);
int __cdecl CBattle_Field::SetDamageValue(CBattle_Field *this, int id, int value);
void __cdecl CBattle_Field::MakePacket(CBattle_Field *this, int id, InterfacePacketBuf *a3);
int __cdecl CBattle_Field::check_grid_clear(CBattle_Field *this);
bool __cdecl CBattle_Field::reset_hell_party_value(CBattle_Field *this);
int __cdecl CBattle_Field::GetFieldMob(CBattle_Field *this, int id, map_monster *a3);
int __cdecl CBattle_Field::convertAPCRoleType2MonsterRoleType(CBattle_Field *this, unsigned __int8 a2);
CParty *__cdecl CBattle_Field::check_random_appear_hell_dungeon(CParty **a1, CDungeon *dungeon, int id, int value, _BYTE *a5);
int __cdecl CBattle_Field::getItemDropDungeonType(CBattle_Field *this);
int __cdecl CBattle_Field::getRandomBuffDungeonType(CBattle_Field *this, int index);
int __cdecl CBattle_Field::setEplpWaitingTimer(int *a1, int id);
void __cdecl CBattle_Field::_MakeDropItems(CDungeon **a1, int id, int value, int count, __int16 a5, int index, int type, int result, char flag, std::_Bit_iterator *a10, int status, int id2);
int __cdecl CBattle_Field::setPremiumDropRate(CDungeon **a1, int id, int value);
void __cdecl CBattle_Field::_MakeNotiPacketDieMonster(CBattle_Field *battlefield, PacketBuf **a2, int *a3, __int16 a4, __int16 a5, int id, int value);
int __cdecl CBattle_Field::kill_monster(CBattle_Field *this, PacketBuf **a2, char **a3, unsigned int *a4, const STKillMonsterData *a5);
int __cdecl CBattle_Field::kill_blood_monster(CBattle_Field *this, CUser *user, int id, unsigned __int16 *a4);
void __cdecl CBattle_Field::KillHellPartyGroupMonsterCnt(CBattle_Field *this, MapInfo *a2, map_monster *a3, bool *a4);
void __cdecl CBattle_Field::send_elevator_time_packet(CBattle_Field *this, char flag);
void __cdecl CBattle_Field::check_elevator_timer(CBattle_Field *this);
int __cdecl CBattle_Field::get_field_item(CBattle_Field *this, int id, map_item *a3);
_BOOL4 CBattle_Field::is_last_field_item(CBattle_Field *this, ...);
int CBattle_Field::pickup_item(CBattle_Field *this, ...);
int __cdecl CBattle_Field::drop_item(CBattle_Field *battlefield, int id, int value);
_DWORD *__cdecl CBattle_Field::onUseItem(CBattle_Field *this, CUser *user, const Inven_Item *item);
int __cdecl CBattle_Field::onStartMap(CBattle_Field *this);
char __cdecl CBattle_Field::onClearMap(CBattle_Field *this, bool a2);
int __cdecl CBattle_Field::GetTotalSkillMaterial(CBattle_Field *this);
int __cdecl CBattle_Field::getLayeredMapIndex(CBattle_Field *this);
CBattle_Field *__cdecl CBattle_Field::setLayeredMapIndex(CBattle_Field *this);
int __cdecl CBattle_Field::getLayeredMapKeyValue(CBattle_Field *this, int id);
int __cdecl CBattle_Field::getCurrentLayeredMapInfo(CBattle_Field *this);
int __cdecl CBattle_Field::getLayeredMapInfoIndex(CBattle_Field *this, int id);
bool __cdecl CBattle_Field::setQuestMazeInfo(CBattle_Field *this);
CBattle_Field *__cdecl CBattle_Field::setQuestMaze(CBattle_Field *this, bool a2);
int __cdecl CBattle_Field::isQuestMaze(CBattle_Field *this);
int __cdecl CBattle_Field::checkLayeredMap(CBattle_Field *this, int id, int value);
int `global constructor keyed to'CBattle_Field::SetTournamentCurRound();
int __cdecl CBattle_Field::GetLastMapInfo(CBattle_Field *this);
int __cdecl CBattle_Field::getBloodMaxRound(CBattle_Field *this);
int __cdecl CBattle_Field::CheckAppearRidableObject(CBattle_Field *this, PacketBuf **a2);
int CBattle_Field::IsEnableHellDungeon();
CBattle_Field *__cdecl CBattle_Field::set_dungeon_diff(CBattle_Field *this, char flag);
int __cdecl CBattle_Field::GetMonsterMap(CBattle_Field *this);
int __cdecl CBattle_Field::setBloodState(int id, int value);
int __cdecl CBattle_Field::SetRidableObjectState(int id, int value, int count);
int __cdecl CBattle_Field::IsKilledAllHellGruoups(CBattle_Field *this);
int __cdecl CBattle_Field::get_map_index(MazeScript **this, int id, int value);
int __cdecl CBattle_Field::GetCurrentMap(CBattle_Field *this);
_BOOL4 __cdecl CBattle_Field::ClearCondition(int id, unsigned int value, int count);
int __cdecl CBattle_Field::IsVisitedCurrentMap(CBattle_Field *this);
CBattle_Field *__cdecl CBattle_Field::setWorldMapTowerArea(CBattle_Field *this, bool a2);
int __cdecl CBattle_Field::isWorldMapTowerArea(CBattle_Field *this);
int __cdecl CBattle_Field::GetCurPosX(CBattle_Field *this);
int __cdecl CBattle_Field::GetCurPosY(CBattle_Field *this);
int __cdecl CBattle_Field::SetAssignNPCByPotion(CBattle_Field *this, bool a2);

#endif // CBATTLE_FIELD_H
