#ifndef CPARTY_H
#define CPARTY_H

#include <common/defs.h>

// CParty declarations
int __cdecl CParty::get_user(CParty *this, int id);
int __cdecl CParty::getManager(CParty *this);
char __cdecl CParty::SetEPLPState(CParty *this, char flag);
int __cdecl CParty::GetEPLPState(CParty *this);
CParty *__cdecl CParty::SetSelectedEPLPCmd(CParty *this, char flag);
_BOOL4 __cdecl CParty::IsRoutingState(CParty *this);
int __cdecl CParty::checkValidUser(CUser **this, int id);
char *__cdecl CParty::getMemberNames(CUserCharacInfo **this, char *s);
long double __cdecl CParty::getAvatarBonus(CUser **this);
long double __cdecl CParty::getCreatureBonus(CParty *this, CUser *user);
int __cdecl CParty::getMemberLevelGap(CUserCharacInfo **this);
int __cdecl CParty::IsSinglePlay(CParty *this);
CParty *__cdecl CParty::SetRecvResultFlag(CParty *this, bool a2);
int __cdecl CParty::get_state(CParty *this);
int __cdecl CParty::GetPartyIndex(CParty *this);
CParty *__cdecl CParty::setDungIndex(CParty *this, unsigned __int16 a2);
CParty *__cdecl CParty::setDungDiffi(CParty *this, unsigned __int8 a2);
int __cdecl CParty::IsAutoCreated(CParty *this);
int __cdecl CParty::get_dungeon_clear_state(CParty *this);
CParty *__cdecl CParty::set_dungeon_clear_state(CParty *this, CParty *party);
CParty *__cdecl CParty::IncreaseUsedCoinCount(CParty *this);
int __cdecl CParty::GetUsedCoinCount(CParty *this);
_BOOL4 __cdecl CParty::checkBossRoom(CParty *this);
char *__cdecl CParty::GetPartyTelePort(CParty *this);
char *__cdecl CParty::GetMember(CParty *this);
int __cdecl CParty::get_quick_party_index(CParty *this);
CParty *__cdecl CParty::set_quick_party(CParty *this, bool a2);
int __cdecl CParty::is_quick_party(CParty *this);
int __cdecl CParty::set_gm_random_buff_type(int id, int value);
_BOOL4 __cdecl CParty::checkStartRoom(CParty *this);
CParty *__cdecl CParty::SetSinglePlay(CParty *this, bool a2);
CParty *__cdecl CParty::set_state(CParty *this, char flag);
CParty *__cdecl CParty::SetAutoCreated(CParty *this, bool a2);
CParty *__cdecl CParty::set_quick_party_index(CParty *this, int id);
int __cdecl CParty::IsFirstMapClear(CParty *this);
CParty *__cdecl CParty::SetFirstMapClear(CParty *this, bool a2);
void __cdecl CParty::CParty(CParty *this);
char *__cdecl CParty::getTitle(CParty *this);
int __cdecl CParty::getTitleIndex(CParty *this);
int __cdecl CParty::getUserMax(CParty *this);
int __cdecl CParty::getDungIndex(CParty *this);
int __cdecl CParty::getDungDiffi(CParty *this);
CParty *__cdecl CParty::SetAssaultState(CParty *this, char flag);
int __cdecl CParty::IsExistUser(CUser **this, CUser *user);
int __cdecl CParty::getStraightVictories(CParty *this);
CParty *__cdecl CParty::incStraightVictories(CParty *this);
CParty *__cdecl CParty::resetStraightVictories(CParty *this);
int __cdecl CParty::get_random_buff_type(CParty *this);
int __cdecl CParty::GetSelectedEPLPCmd(CParty *this);
CParty *__cdecl CParty::setStraightVictories(CParty *this, unsigned __int16 a2);
CParty *__cdecl CParty::setDungeonMapSaving(CParty *this, bool a2);
char *__cdecl CParty::getPassedMapInfoList(CParty *this);
int __cdecl CParty::Get_party_overlapped_drop_ratio_rare(CParty *this);
int __cdecl CParty::Get_party_overlapped_drop_ratio_unique(CParty *this);
int __cdecl CParty::get_member_count(CUser **this);
int __cdecl CParty::get_total_level(CUserCharacInfo **this);
int __cdecl CParty::is_limit_minimum_age(CUser **this, unsigned int id, int *a3);
int __cdecl CParty::is_limit_minimum_level(CUser **this, int id, int *a3);
_BOOL4 __cdecl CParty::CanDoPartyActionAssalutState(CParty *this);
int __cdecl CParty::TimeoutCompleteAfterAssault(CParty *this);
char CParty::ConnectP2P(CParty *this, CUser *user, char *src, ...);
_BOOL4 __cdecl CParty::_IsCannotConnectP2P(CParty *this, int id, int value);
int __cdecl CParty::_ClearConnectP2PAbsolute(std::string **this, int id);
int __cdecl CParty::_ClearConnectP2PRelative(std::string **this, int id);
int __cdecl CParty::_GetConnectP2PPoint(CParty *this, int id);
bool __cdecl CParty::_GetConnectP2PMaxMinPoint(CParty *this, int *a2, int *a3);
char __cdecl CParty::ClearBadP2PUser(std::string **this);
int __cdecl CParty::get_live_count(CUser **this);
int __cdecl CParty::get_live_count_enter_map(CUser **this);
int __cdecl CParty::GetMemberSlotNo(const CUser **this, const CUser *user);
int __cdecl CParty::GetMemberSlotNo(CParty *this, unsigned int id);
int __cdecl CParty::gen_timer_key(int id, int value);
bool __cdecl CParty::check_timer_key(int id, int value, int count);
int __cdecl CParty::set_single_play(CParty *this, CUser *user);
int __cdecl CParty::create_party(CParty *this, CUser *user);
CParty *__cdecl CParty::SetPartyInfoUI(CParty *party, int id);
int __cdecl CParty::join_user(CParty *this, CUser *user);
CParty *__cdecl CParty::init_quick_party_data(CParty *this);
int __cdecl CParty::change_manager_for_quick_party(pthread_mutex_t **this);
int __cdecl CParty::delete_party_for_quick_party(CUser **a1, CUser *user, int id);
void __cdecl CParty::send_quick_party_matching_result(CUser **this, char flag, CUser *user);
int __cdecl CParty::choose_random_buff(CParty *party, int id); // idb
int __cdecl CParty::set_random_reward(CParty *party, unsigned int id, int value, int count, int index);
char __cdecl CParty::set_basic_reward(CParty *party, unsigned int id, int value, int count, int index);
bool __cdecl CParty::increase_result_card_gold(CParty *this, WongWork::stGenerateResult_t *a2);
bool __cdecl CParty::increase_hell_party_ratio(CUserCharacInfo **this, char *a2);
CParty *__cdecl CParty::increase_dungeon_coin_count(CParty *this, int id);
char __cdecl CParty::increase_ancient_dungeon_ticket(CParty *this);
char __cdecl CParty::increase_dimension_inout_count(CParty *this, int id);
int __cdecl CParty::leave_user(std::string **a1, std::string *a2, int id);
int __cdecl CParty::change_manager(pthread_mutex_t **this);
int __cdecl CParty::change_manager(CParty *this, CUser *user, unsigned int id);
int __cdecl CParty::walkout_member(CUser **this, CUser *user, int id);
int __cdecl CParty::SendWalkout(CUser **a1, char flag, char type);
int __cdecl CParty::get_party_realtime_info(CUser **this, PacketBuf **a2);
void __cdecl CParty::send_party_realtime_info(CUser **this);
int __cdecl CParty::set_host(CParty *this);
void __cdecl CParty::send_host_info(CUser **this);
void __cdecl CParty::send_party_ipinfo(CUser **this);
bool __cdecl CParty::send_to_party(CUser **this, PacketGuard *a2);
void __cdecl CParty::send_to_party_cmd_error(CUser **a1, __int16 a2, char flag);
void __cdecl CParty::send_invite_pvp(CUser **this, __int16 a2);
void __cdecl CParty::send_invite_warroom(CUser **this, __int16 a2);
void __cdecl CParty::send_invite_bluemarble(CUser **this, __int16 a2);
int __cdecl CParty::CheckMemberFatigue(CUser **this);
int __cdecl CParty::CheckMemberArea(CUser **this);
int CParty::MemberPenaltyRate();
int __cdecl CParty::make_blood_dungeon_info(CParty *this, CUser *user, PacketBuf **a3);
int __cdecl CParty::make_blood_dungeon_info_blank(CUser **this, PacketBuf **a2);
_BOOL4 __cdecl CParty::CheckEnterAncientDungeon(CUserCharacInfo **this, const CDungeon *dungeon, unsigned __int8 *a3, Inven_Item *item, int *a5);
_BOOL4 __cdecl CParty::CheckEnterAncientDungeon(CUserCharacInfo **this, char **a2);
int __cdecl CParty::UseAncientDungeonItems(CParty *this, const CDungeon *dungeon, Inven_Item *item, int *a4);
int __cdecl CParty::CheckEnterEventDungeon(CUserCharacInfo **this, const CDungeon *dungeon, unsigned __int8 *a3, Inven_Item *item, int *a5);
int __cdecl CParty::CheckEnterDimensionDungeon(CUser **this, const CDungeon *dungeon, unsigned __int8 *a3, bool a4);
int __cdecl CParty::CheckEnterDimensionDungeon(CParty *this, const CDungeon *dungeon, unsigned __int8 *a3, char flag);
int __cdecl CParty::CheckEnterDimensionDungeon(CDungeon **this, const CDungeon *dungeon);
int __cdecl CParty::getPartyMemberAvgLevel(CUserCharacInfo **this);
int __cdecl CParty::setStandardDimensionLevel(CUser **this);
int __cdecl CParty::getStandardDimensionLevel(CParty *this);
int __cdecl CParty::checkDugeonInoutTime(CUser **this, int id);
int __cdecl CParty::get_blood_dungeon_admission_fee(CParty *this, CUser *user);
int __cdecl CParty::check_dungeon_start(CParty *this, const CDungeon *dungeon, int *a3);
int __cdecl CParty::check_dungeon_start(CParty *this, const CDungeon *dungeon);
int __cdecl CParty::do_after_dungeon_start(CParty *this, const CDungeon *dungeon, CUser *user);
int __cdecl CParty::do_after_dungeon_start_checkndelete_item(CParty *this, const RequiredItem *a2, CUser *user);
int __cdecl CParty::dungeon_start(CParty *party, char *a2, char flag, int id);
int __cdecl CParty::FindUserByCharId(CParty *this, unsigned int id);
int CParty::isHelpAbuseParty();
int __cdecl CParty::isHelpAbuseParty(CParty *this);
int __cdecl CParty::SelectEPLPCommand(CParty *this, int id);
int __cdecl CParty::GetExpPenaltyPercent(CParty *this, int id, int value);
int __cdecl CParty::getMonsterTotalExp(CParty *this, unsigned int id, char flag, int value, float a5, float a6, bool a7);
int __cdecl CParty::sumGainedEachExp(CParty *this, CUser *user, const STGainedEachExpData *a3);
int __cdecl CParty::get_party_seatno(CUser **this, CUser *user);
int __cdecl CParty::kill_monster(CParty *party, CUser *user, __int16 a3, unsigned __int16 a4, int id, _IO_FILE **a6);
int __cdecl CParty::kill_blood_monster(CParty *this, CUser *user, int id, unsigned __int16 *a4);
int __cdecl CParty::get_item(const CUser **this, CUser *user, unsigned int id, bool a4, char flag, int *a6, unsigned __int8 *a7, bool *a8);
int __cdecl CParty::drop_item(CUser **this, CUser *user, __int16 a3, __int16 a4, char flag, int id, int value);
int __cdecl CParty::drop_item_gm(CUser **this, CUser *user, unsigned int id);
_BOOL4 __cdecl CParty::isMonsterDrop_item(CParty *this, int id);
int __cdecl CParty::use_skill(CParty *this, CUser *user, int id);
_DWORD *__cdecl CParty::useItem(CParty *this, CUser *user, const Inven_Item *item);
void __cdecl CParty::die_user(CParty *this, CUser *user);
bool __cdecl CParty::CheckClearQuestHellParty(CParty *party, int *a2);
int __cdecl CParty::CheckHaveHellPartyPassItem(CParty *party, CDungeon *dungeon, int id);
int __cdecl CParty::CheckDestroyConditionSealDoor(CParty *party, CDungeon *dungeon, int id, _DWORD *a4);
int __cdecl CParty::UseSealDoorItems(CParty *party, _DWORD *a2);
int __cdecl CParty::IsClearedQuest(CUser **this, unsigned int id);
_BOOL4 __cdecl CParty::CheckHellCoinLimint(CParty *this, int id);
int __cdecl CParty::checkMoveMapHackCnt(CParty *party, int id); // idb
_BOOL4 __cdecl CParty::canFatigueUp(CParty *this);
int __cdecl CParty::changePartyMemberInfo(CUser **a1, int id, char flag);
bool __cdecl CParty::resetFinishLoadingVar(CParty *this);
char __cdecl CParty::changePartyMemberInfoOnMoveMap(CUser **a1, int id, char flag);
CParty *__cdecl CParty::changeBattleDataOnMoveMap(CParty *this, bool a2);
int __cdecl CParty::move_map(CParty *party, int id); // idb
void CParty::check_passive_skill();
int __cdecl CParty::OnTimeoutBossDie(CParty *this, int id, unsigned int value);
int __cdecl CParty::_putItemIntoUser(CUser **this, CUser *user, Inven_Item *item, PacketBuf **a4);
int __cdecl CParty::checkInoutConditionDungeon(CUser **a1, CDungeon *dungeon, int id, int value);
void __cdecl CParty::sendInoutConditionDungeon(CUser **a1, int id);
int __cdecl CParty::sendPremiumGoldCardStatistic(CParty *this, char flag, int id, int value);
long double __cdecl CParty::CalcAvatarBonus(CUser **this);
long double __cdecl CParty::CalcCreatureBonus(CParty *this, CUser *user);
int __cdecl CParty::_makeRewardItemInfo(CParty *this, const CUser *user, Inven_Item *item, PacketBuf **a4);
char *__cdecl CParty::getClearRewardBonusExp(CParty *this, CUser *user, unsigned int *a3, const stClearRewardExpParameter_t *a4, size_t *__a);
long double __cdecl CParty::calDeadUserDungeonPenalty(CParty *this, int id);
long double __cdecl CParty::CalcurateManageBonus(int id, int value, CUserCharacInfo *charac_info, int count);
void __cdecl CParty::set_clear_reward_exp_parameter(CUser **this, CUser *user, unsigned int id, stClearRewardExpParameter_t *a4);
int __cdecl CParty::isPremiumGoldCardReward(CParty *this, const CDungeon *dungeon, unsigned int *a3);
char __cdecl CParty::DungeonPermission(CParty *this, int id);
int __cdecl CParty::send_loadingcheck_msg(CParty *this);
int __cdecl CParty::set_play_result(CUser **this, CUser *user);
int __cdecl CParty::insert_time_dungeon_clear_msg(CParty *this, int id);
int __cdecl CParty::insert_time_card_select_msg(CParty *this, int id);
int __cdecl CParty::insert_time_clear_dungeon_reward_msg(CParty *this, int id);
int __cdecl CParty::insert_time_dungeon_score_scroll_msg(CParty *this, int id);
int __cdecl CParty::insert_time_card_select_right_msg(CParty *this, int id);
int __cdecl CParty::IncreaseSetPlayResultCount(const CUser **this, CUser *user);
int __cdecl CParty::GetSetPlayResultCount(CParty *this);
const char *__cdecl CParty::GetNoSendSetPlayResultUser(CUserCharacInfo **this, int id);
int __cdecl CParty::SetPlayResult(CParty *this, CUser *user);
void __cdecl CParty::forced_set_play_result(CUser **this);
int __cdecl CParty::ReviveUser(CParty *this, CUser *user, unsigned __int16 a3);
void __cdecl CParty::set_charac_live(CParty *party, CUser *user, unsigned int id);
int __cdecl CParty::check_allmember_die(CUser **this);
bool __cdecl CParty::SaveCoin(CUser **a1);
int __cdecl CParty::GetCoinCount(CParty *this, CUser *user);
int __cdecl CParty::send_dungeon_fail_msg(CParty *this);
int __cdecl CParty::VoteLackUser(CParty *this, CUser *user, unsigned int id);
int __cdecl CParty::OnTimerWalkOutLackUser(CParty *this);
int __cdecl CParty::set_recv_party_packet_flag(const CUser **this, CUser *user);
int __cdecl CParty::recv_party_packet_all(CUser **this);
int __cdecl CParty::CheckRecvFromAllMember(const CUser **this, CUser *user);
int __cdecl CParty::HaveAlreadySelectedCard(int id, char flag, int value);
int __cdecl CParty::_checkGoldCardSelectable(int id, CUserCharacInfo *charac_info, unsigned int value, unsigned int count);
int __cdecl CParty::SetCardNumber(const CUser **a1, CUserCharacInfo *charac_info, char flag, int id);
void __cdecl CParty::SendEachCardInfo(CParty *this);
int __cdecl CParty::IsSelectCard(int id, char flag, int value);
bool __cdecl CParty::CompleteCardSelect(CParty *this);
int __cdecl CParty::IsCompleteCardSelectOfMembers(int id, int value);
void __cdecl CParty::SendCardSelectComplete(CUser **this);
int __cdecl CParty::isGuildParty(CUserCharacInfo **this);
int __cdecl CParty::hasPCRoomPlayer(CUser **this);
int __cdecl CParty::_getMemberLevelGap(CUserCharacInfo **this);
char *__cdecl CParty::_getMemberNames(CUserCharacInfo **this, char *s);
int __cdecl CParty::_checkValidUser(CUser **this, int id);
int __cdecl CParty::SendDungeonCharacInfo(CParty *this, CUser *user, bool a3);
int __cdecl CParty::SendDungeonStatisticParty(CParty *this, bool a2, CUser *user);
int __cdecl CParty::SendDungeonStatisticPartyJob(CParty *this, bool a2, CUser *user);
int __cdecl CParty::SendDungeonStatisticPartyCharac(CParty *this, bool a2, CUser *user);
void __cdecl CParty::cal_hellparty_value(CParty *this, int id, int value, int count);
int __cdecl CParty::get_rate_level_difference(CParty *this);
int __cdecl CParty::OnKilledMonster(CParty *party, CUser *user, int id, int value, int count); // idb
int __cdecl CParty::OnUsedSkill(CParty *this, CUser *user, int id);
int __cdecl CParty::getMemberMinLevel(CUserCharacInfo **this);
int __cdecl CParty::getMemberMaxLevel(CUserCharacInfo **this);
int __cdecl CParty::getMemberMaxLevelBeforeDungeon(CUserCharacInfo **this);
bool __cdecl CParty::GetLuckPoint(CUser **this, CLuckPoint *a2, bool a3);
int __cdecl CParty::IsExistCharacter(CUser **this, int id);
int __cdecl CParty::GetPartyType(CUserCharacInfo **this);
int __cdecl CParty::IsExistInvisible(CUser **this);
int __cdecl CParty::CheckQuestConnection(CUser **a1, unsigned int id, int value);
int __cdecl CParty::HasNoQuestGoWithApcInParty(CUser **this, const Quest *a2);
char __cdecl CParty::enumPartyMember(CParty *this, bool (*a2)(CUser *));
int __cdecl CParty::isMyMember(CUser **this, unsigned int id);
__int64 __cdecl CParty::GetMapPlayingTime(CParty *this);
int __cdecl CParty::existSamePCRoomUser(CUser **this, unsigned int id);
int __cdecl CParty::isSamePCRoomParty(CUser **this);
void __cdecl CParty::sub_hellparty_value(CParty *this);
void __cdecl CParty::send_hellParty_value(CParty *this);
bool __cdecl CParty::historyBloodRoundClear(CUserCharacInfo **this, int id, unsigned int value, unsigned int count, const char *a5);
CBattle_Field::CBloodClearRewardData *__cdecl CParty::generateBloodRewardExp(CDungeon **this, int id, int value, unsigned int count, __int16 a5);
void __cdecl CParty::generateBloodRewardItem(CUser **this, int id, int value, char flag, unsigned int count, bool a6);
int __cdecl CParty::checkBloodRenewMyRecord(CUserCharacInfo **this, int id, unsigned int value, int count, int index);
void __cdecl CParty::BloodClearRewardPacket(CUser **this, int id, char flag, int value, const Inven_Item *item, int count, const Inven_Item *item, int index, const Inven_Item *item, int type, const Inven_Item *item);
int __cdecl CParty::BloodHandleDieUser(CParty *this, CUser *user);
int __cdecl CParty::IsThereGhostInParty(CUser **this);
_BOOL4 __cdecl CParty::getMemberPassParty(CUserCharacInfo **this, CUser *user);
char __cdecl CParty::Reset_party_overlapped_drop_ratio(CParty *this);
char __cdecl CParty::_onGetItem(CParty *this, CUser *user, unsigned int id, unsigned __int16 a4);
int __cdecl CParty::GetUserPosition(CUser **this, CUser *user);
CUser **__cdecl CParty::GetUserSecretShop(CUser **this, CUser *user);
void __cdecl CParty::SendSecretShopItemList(CUser **this, CUser *user);
int __cdecl CParty::SetRidableObjectState(int id, int value, int count);
int __cdecl CParty::IsReturnUserParty(CUser **this);
int __cdecl CParty::IsEventCharacParty(CUserCharacInfo **this);
char __cdecl CParty::SetMemberRoutingState(CParty *this, CUser *user, char flag);
int __cdecl CParty::GetMemberRoutingState(CParty *this, CUser *user);
int __cdecl CParty::HasAllMemberSelection(CUser **this);
bool __cdecl CParty::SetRoutingTimerOver(CParty *this);
bool __cdecl CParty::GetRoutingDiceMemberList(CUserCharacInfo **a1, _DWORD *a2, CItem *a3);
int __cdecl CParty::GetFirstValidMemberState(CUser **this);
bool __cdecl CParty::send_to_alive_member(CUser **this, PacketGuard *a2);
int __cdecl CParty::switchPostion(CParty *this, char flag, char type);
bool __cdecl CParty::setMonsterMoveHack(CParty *this);
int __cdecl CParty::CheckEnterVillageAttackRevenge(CUser **this, const CDungeon *dungeon);
int __cdecl CParty::OnTODRewardTimer(CParty *party, int id); // idb
int __cdecl CParty::_Send_TOD_ClearReward(CParty *this);
int __cdecl CParty::_Send_TOD_APCInfo(CDungeon **this, int id);
int __cdecl CParty::GetDungeonIndex_isTOD(CParty *this, int *a2, int *a3);
char __cdecl CParty::MemberRegisterKillMonster(CParty *this, char **a2, unsigned __int8 a3);
char __cdecl CParty::CheckHackAverageHitCount(CParty *this);
_BOOL4 __cdecl CParty::isCheckUseSkill(CParty *this, int id, int value);
int __cdecl CParty::SetProperDungeonEvent(CDungeon **this, CUser *user);
CUser *__cdecl CParty::SetProperLevelDungeon(CDungeon **this, CUser *user);
_BOOL4 __cdecl CParty::CheckHellDungeonFreepassItemHaveAndDel(CParty *this, CUser *user, bool a3);
CParty *__cdecl CParty::SetWeekendEvent(CParty *this, bool a2);
int __cdecl CParty::IsWeekendEvent(CParty *this);
int __cdecl CParty::CheckMemberLastTryAssaultTime(CParty *this);
bool __cdecl CParty::GetValidPartyMember(CUser **a1, int *a2);
void __cdecl CParty::TournamentDungeonClear(CParty *this, bool a2);
int __cdecl CParty::GetTournamentDungeonClearState(CParty *this);
CParty *__cdecl CParty::SetTournamentDungeonClearState(CParty *this, CParty *party);
int __cdecl CParty::InsertTournamentDungeonTimer(int id, int value);
int __cdecl CParty::isTournamentVictory(CParty *this);
char __cdecl CParty::MakeQuestRewardPacket(CParty *this, PacketBuf **a2, CUser *user);
int __cdecl CParty::GetPartyMemberForceDropFlag(CParty *this);
int __cdecl CParty::getDungeonDropTestFlag(CParty *this);
bool __cdecl CParty::resetMemberUseCoin(CParty *this);
int __cdecl CParty::getDungeonTypeKind(CParty *this, const CDungeon *dungeon);
int __cdecl CParty::addDungeonClear(CParty *this, const CDungeon *dungeon, int id, int value);
void __cdecl CParty::SendPartyMemberTagChracInfo(CParty *this);
bool __cdecl CParty::setBestClearTime(CParty *this, char flag, int id, int value);
bool __cdecl CParty::makeBestClearTimePacket(CUser **this, PacketBuf **a2, int id);
_BOOL4 __cdecl CParty::checkFreeRevivalCondition(CParty *this, const CDungeon *dungeon);
_BOOL4 __cdecl CParty::checkUnLimitUsedCoinCondition(CParty *this, const CDungeon *dungeon);
int __cdecl CParty::GetPartyMemberCoinLimit(CParty *this);
CParty *__cdecl CParty::SetPartyMemberCoinLimit(CParty *this, int id);
int __cdecl CParty::checkLimitUsedCoinCondition(CParty *this, const CDungeon *dungeon);
_BOOL4 __cdecl CParty::isDungeonDifficultyInfromNotice(CUserCharacInfo **this, bool a2);
_BOOL4 __cdecl CParty::checkDungeonDifficulty(CUser **this, char flag, const CDungeon *dungeon);
_BOOL4 __cdecl CParty::IsUseFatigueDungeon(CParty *this);
int __cdecl CParty::CheckMapClear(CParty *this);
void *__cdecl CParty::reset_recv_flag(CParty *this);
int __cdecl CParty::IsPremiumGoldCardParty(CParty *this);
CParty *__cdecl CParty::SetPremiumGoldCardParty(CParty *this);
CParty *__cdecl CParty::ResetPremiumGoldCardParty(CParty *this);
int __cdecl CParty::GetPremiumGoldCardDefaultItem(CParty *this);
CParty *__cdecl CParty::SetPremiumGoldCardDefaultItem(CParty *this, unsigned int id);
CParty *__cdecl CParty::ResetPremiumGoldCardDefaultItem(CParty *this);
CParty *__cdecl CParty::setStartGamePartyCount(CParty *this, int id);
int __cdecl CParty::getStartGamePartyCount(CParty *this);
char *__cdecl CParty::setTitle(CParty *this, char *src);
CParty *__cdecl CParty::setTitleIndex(CParty *this, unsigned __int8 a2);
CParty *__cdecl CParty::setUserMax(CParty *this, unsigned __int8 a2);
int __cdecl CParty::GetAssaultState(CParty *this);
bool __cdecl CParty::SetEndRouting(CParty *this);
CParty *__cdecl CParty::SetUsedCoinCount(CParty *this, int id);
CParty *__cdecl CParty::ClearMapHitCount(CParty *this);
int __cdecl CParty::getDungeonMapSaving(CParty *this);
unsigned __int8 __cdecl CParty::SetStartRouting(CParty *this);
CParty::CItemRoutingData *__cdecl CParty::SetRoutingItem(CParty *this, Inven_Item *item, unsigned int id);
int __cdecl CParty::GetRoutingItemID(CParty *this);
char *__cdecl CParty::GetRoutingInvenItem(CParty *this);
int __cdecl CParty::GetRoutingItemUniqueID(CParty *this);
int __cdecl CParty::DeleteDungeonDropItem(CParty *this, int id);
char *__cdecl CParty::GetSecretShopData(CParty *this);

#endif // CPARTY_H
