#!/usr/bin/env python3
"""
df_game_r.c File Splitter
Splits the large df_game_r.c file into manageable chunks for faster compilation.
"""

import os
import sys

# Configuration
INPUT_FILE = "df_game_r.c"
DECLARATION_HEADER = "df_game_r_decl.h"
OUTPUT_DIR = "src_split"
LINES_PER_FILE = 100000  # Target lines per file
DECLARATION_LINE_END = 97296  # Line where function declarations end

def count_braces(line):
    """Count opening and closing braces in a line"""
    return line.count('{') - line.count('}')

def find_function_boundary(lines, start_idx, target_lines):
    """
    Find a good split point near target_lines that's at a function boundary.
    Returns the line index where the next file should start.
    """
    target_idx = min(start_idx + target_lines, len(lines))
    brace_depth = 0

    # Count braces from start to target
    for i in range(start_idx, target_idx):
        brace_depth += count_braces(lines[i])

    # Move forward until we find a function boundary (brace_depth == 0)
    idx = target_idx
    while idx < len(lines) and brace_depth != 0:
        brace_depth += count_braces(lines[idx])
        idx += 1

    # If we couldn't find a boundary within reasonable distance,
    # just split at target
    if idx - target_idx > LINES_PER_FILE // 2:
        return target_idx

    return idx

def split_file():
    """Main function to split the source file"""
    print(f"Reading {INPUT_FILE}...")

    # Read entire file
    with open(INPUT_FILE, 'r', encoding='utf-8', errors='ignore') as f:
        lines = f.readlines()

    total_lines = len(lines)
    print(f"Total lines: {total_lines:,}")
    print(f"Declaration section: lines 1-{DECLARATION_LINE_END:,}")
    print(f"Implementation section: lines {DECLARATION_LINE_END+1:,}-{total_lines:,}")

    # Create output directory
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Step 1: Extract declarations to header file
    print(f"\n1. Creating {DECLARATION_HEADER}...")
    header_content = [
        "/* Function declarations extracted from df_game_r.c */\n",
        "/* Generated by split_source.py */\n",
        "\n",
        "#ifndef DF_GAME_R_DECL_H\n",
        "#define DF_GAME_R_DECL_H\n",
        "\n",
        "#include <math.h>\n",
        "#include <defs.h>\n",
        "#include <stdarg.h>\n",
        "\n",
    ]
    header_content.extend(lines[13:DECLARATION_LINE_END])  # Skip initial comments and includes
    header_content.append("\n#endif /* DF_GAME_R_DECL_H */\n")

    header_path = os.path.join(OUTPUT_DIR, DECLARATION_HEADER)
    with open(header_path, 'w', encoding='utf-8') as f:
        f.writelines(header_content)

    print(f"   Created: {header_path} ({len(header_content):,} lines)")

    # Step 2: Split implementation into multiple files
    print(f"\n2. Splitting implementation section...")
    print(f"   Target lines per file: {LINES_PER_FILE:,}")

    impl_start = DECLARATION_LINE_END
    current_idx = impl_start
    file_num = 1

    while current_idx < total_lines:
        # Find next split point
        remaining = total_lines - current_idx
        if remaining <= LINES_PER_FILE * 1.2:  # If close to end, put rest in one file
            next_idx = total_lines
        else:
            next_idx = find_function_boundary(lines, current_idx, LINES_PER_FILE)

        # Create part file
        part_filename = f"df_game_r_part{file_num:02d}.c"
        part_path = os.path.join(OUTPUT_DIR, part_filename)

        part_content = [
            f"/* Part {file_num} of df_game_r implementation */\n",
            f"/* Lines {current_idx+1:,}-{next_idx:,} of original file */\n",
            "/* Generated by split_source.py */\n",
            "\n",
            "#include \"df_game_r_decl.h\"\n",
            "\n",
        ]
        part_content.extend(lines[current_idx:next_idx])

        with open(part_path, 'w', encoding='utf-8') as f:
            f.writelines(part_content)

        part_lines = next_idx - current_idx
        print(f"   Part {file_num:2d}: {part_filename:25s} "
              f"({part_lines:7,} lines, {current_idx+1:,}-{next_idx:,})")

        current_idx = next_idx
        file_num += 1

    # Step 3: Create updated Makefile
    print(f"\n3. Creating updated Makefile...")
    create_makefile(file_num - 1)

    # Summary
    print(f"\n{'='*60}")
    print(f"Split complete!")
    print(f"  - Declaration header: {DECLARATION_HEADER}")
    print(f"  - Implementation files: {file_num-1} parts (df_game_r_part01.c - df_game_r_part{file_num-1:02d}.c)")
    print(f"  - Output directory: {OUTPUT_DIR}/")
    print(f"\nNext steps:")
    print(f"  1. Review files in {OUTPUT_DIR}/")
    print(f"  2. Copy Makefile.split to project root or use directly")
    print(f"  3. Build with: make -f Makefile.split all")
    print(f"{'='*60}")

def create_makefile(num_parts):
    """Create Makefile for split source files"""
    makefile_content = f"""# Makefile for split df_game_r source files
# Generated by split_source.py

# Compiler and flags
CC = gcc
CXX = g++
CFLAGS = -m32 -O2 -g -fPIC -pipe
CXXFLAGS = $(CFLAGS)
LDFLAGS = -m32 -Wl,-Map,build.map

# Libraries
LIBS = -lpthread -lrt -ldl -lm -lmysqlclient -lGeoIP

# Source directory
SRC_DIR = src_split

# Source files
SOURCES = {' '.join([f'$(SRC_DIR)/df_game_r_part{i:02d}.c' for i in range(1, num_parts+1)])}

# Object files
OBJECTS = $(SOURCES:.c=.o)

# Output
OUTPUT = df_game_r
OUTPUT_STRIPPED = df_game_r.stripped

# Targets
.PHONY: all clean stripped verify help config

all: $(OUTPUT)
\t@echo ""
\t@echo "Build complete: $(OUTPUT)"
\t@echo "Size: $$(du -h $(OUTPUT) 2>/dev/null | cut -f1)"
\t@echo ""

$(OUTPUT): $(OBJECTS)
\t@echo "Linking $(OUTPUT)..."
\t$(CXX) $(LDFLAGS) -o $@ $^ $(LIBS)

$(SRC_DIR)/%.o: $(SRC_DIR)/%.c $(SRC_DIR)/df_game_r_decl.h
\t@echo "Compiling $<..."
\t$(CC) $(CFLAGS) -I$(SRC_DIR) -c $< -o $@

stripped: $(OUTPUT)
\t@echo "Creating stripped version..."
\tcp $(OUTPUT) $(OUTPUT_STRIPPED)
\tstrip $(OUTPUT_STRIPPED)
\t@echo "Stripped size: $$(du -h $(OUTPUT_STRIPPED) | cut -f1)"

verify: $(OUTPUT)
\t@echo "Verifying binary..."
\tfile $(OUTPUT)
\t@readelf -h $(OUTPUT) | grep -E "(Class|Machine|Entry|Interpreter)"
\t@echo ""
\t@echo "Dependencies:"
\t@ldd $(OUTPUT) || echo "ldd failed (may be running on incompatible host)"

clean:
\t@echo "Cleaning build artifacts..."
\trm -f $(OBJECTS) $(OUTPUT) $(OUTPUT_STRIPPED) build.map
\t@echo "Clean complete"

config:
\t@echo "Build Configuration:"
\t@echo "  Compiler:    $(CC) / $(CXX)"
\t@echo "  CFLAGS:      $(CFLAGS)"
\t@echo "  LDFLAGS:     $(LDFLAGS)"
\t@echo "  Libraries:   $(LIBS)"
\t@echo "  Source dir:  $(SRC_DIR)"
\t@echo "  Part files:  {num_parts}"
\t@echo "  Objects:     {num_parts}"
\t@echo ""

help:
\t@echo "Available targets:"
\t@echo "  make all       - Build df_game_r with debug symbols (default)"
\t@echo "  make stripped  - Create stripped version"
\t@echo "  make verify    - Verify binary format and dependencies"
\t@echo "  make clean     - Remove build artifacts"
\t@echo "  make config    - Show build configuration"
\t@echo "  make help      - Show this help message"
\t@echo ""
\t@echo "Parallel build:"
\t@echo "  make -j$(shell nproc || echo 4) all  - Build using all CPU cores"
\t@echo ""
"""

    makefile_path = os.path.join(OUTPUT_DIR, "Makefile")
    with open(makefile_path, 'w', encoding='utf-8') as f:
        f.write(makefile_content)

    print(f"   Created: {makefile_path}")
    print(f"   Part files: {num_parts}")
    print(f"   Parallel compilation supported with: make -j{num_parts} all")

if __name__ == "__main__":
    try:
        if not os.path.exists(INPUT_FILE):
            print(f"Error: {INPUT_FILE} not found!")
            sys.exit(1)

        split_file()
        sys.exit(0)

    except KeyboardInterrupt:
        print("\n\nInterrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\nError: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
